/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         startTime: "2024-01-15T09:30:00Z"
 *     }
 */
export interface SessionsStreamRequest {
    /**
     * Optional string of comma separated driver IDs. If driver ID is present, sessions for the specified driver(s) will be returned.
     */
    driverIds?: string | string[];
    /**
     * Optional string of comma separated user IDs. If coach ID is present, sessions for the specified coach(s) will be returned for either assignedCoach or completedCoach. If both driverId(s) and coachId(s) are present, sessions with specified driver(s) and coach(es) will be returned.
     */
    coachIds?: string | string[];
    /**
     * Optional string of comma separated statuses. Valid values:  “upcoming”, “completed”, “deleted”.
     */
    sessionStatuses?: string | string[];
    /**
     * Optional boolean to control whether behaviors will include coachableEvents in the response. Defaults to false.
     */
    includeCoachableEvents?: boolean;
    /**
     * Required RFC 3339 timestamp that indicates when to begin receiving data. Value is compared against `updatedAtTime`
     */
    startTime: string;
    /**
     * Optional RFC 3339 timestamp. If not provided then the endpoint behaves as an unending feed of changes. If endTime is set the same as startTime, the most recent data point before that time will be returned per asset. Value is compared against `updatedAtTime`
     */
    endTime?: string;
    /**
     *  If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.
     */
    after?: string;
    /**
     * Optional boolean indicating whether to return external IDs on supported entities
     */
    includeExternalIds?: boolean;
}
