export * as assets from "./assets/index.js";
export * from "./assets/types/index.js";
export * as inputs from "./inputs/index.js";
export * from "./inputs/types/index.js";
export * as attributes from "./attributes/index.js";
export * from "./attributes/types/index.js";
export * as driverVehicleAssignments from "./driverVehicleAssignments/index.js";
export * from "./driverVehicleAssignments/types/index.js";
export * as drivers from "./drivers/index.js";
export * from "./drivers/types/index.js";
export * as hos from "./hos/index.js";
export * from "./hos/types/index.js";
export * as idling from "./idling/index.js";
export * from "./idling/types/index.js";
export * as liveShares from "./liveShares/index.js";
export * from "./liveShares/types/index.js";
export * as speedingIntervals from "./speedingIntervals/index.js";
export * from "./speedingIntervals/types/index.js";
export * as trips from "./trips/index.js";
export * from "./trips/types/index.js";
export * as alerts from "./alerts/index.js";
export * as auth from "./auth/index.js";
export * as cameras from "./cameras/index.js";
export * as equipment from "./equipment/index.js";
export * as maintenance from "./maintenance/index.js";
export * as reports from "./reports/index.js";
export * as vehicles from "./vehicles/index.js";
export * as addresses from "./addresses/index.js";
export * as contacts from "./contacts/index.js";
export * as defectTypes from "./defectTypes/index.js";
export * as defects from "./defects/index.js";
export * as devices from "./devices/index.js";
export * as driverTrailerAssignments from "./driverTrailerAssignments/index.js";
export * as dvirs from "./dvirs/index.js";
export * as carrierProposedAssignments from "./carrierProposedAssignments/index.js";
export * as documentTypes from "./documentTypes/index.js";
export * as documents from "./documents/index.js";
export * as routes from "./routes/index.js";
export * as safetyEvents from "./safetyEvents/index.js";
export * as trailers from "./trailers/index.js";
export * as legacy from "./legacy/index.js";
export * as formSubmissions from "./formSubmissions/index.js";
export * as forms from "./forms/index.js";
export * as fuelPurchases from "./fuelPurchases/index.js";
export * as gateways from "./gateways/index.js";
export * as issues from "./issues/index.js";
export * as me from "./me/index.js";
export * as readings from "./readings/index.js";
export * as tags from "./tags/index.js";
export * as trainingAssignments from "./trainingAssignments/index.js";
export * as trainingCourses from "./trainingCourses/index.js";
export * as userRoles from "./userRoles/index.js";
export * as users from "./users/index.js";
export * as v1Messages from "./v1Messages/index.js";
export * as webhooks from "./webhooks/index.js";
export * as coaching from "./coaching/index.js";
export * as ifta from "./ifta/index.js";
export * as settings from "./settings/index.js";
export * as tachograph from "./tachograph/index.js";
export * from "./addresses/client/requests/index.js";
export * from "./assets/client/requests/index.js";
export * from "./inputs/client/requests/index.js";
export * from "./attributes/client/requests/index.js";
export * from "./contacts/client/requests/index.js";
export * from "./defectTypes/client/requests/index.js";
export * from "./defects/client/requests/index.js";
export * from "./devices/client/requests/index.js";
export * from "./driverTrailerAssignments/client/requests/index.js";
export * from "./dvirs/client/requests/index.js";
export * from "./carrierProposedAssignments/client/requests/index.js";
export * from "./documentTypes/client/requests/index.js";
export * from "./documents/client/requests/index.js";
export * from "./driverVehicleAssignments/client/requests/index.js";
export * from "./drivers/client/requests/index.js";
export * from "./equipment/client/requests/index.js";
export * from "./hos/client/requests/index.js";
export * from "./routes/client/requests/index.js";
export * from "./safetyEvents/client/requests/index.js";
export * from "./trailers/client/requests/index.js";
export * from "./vehicles/client/requests/index.js";
export * from "./legacy/client/requests/index.js";
export * from "./formSubmissions/client/requests/index.js";
export * from "./forms/client/requests/index.js";
export * from "./fuelPurchases/client/requests/index.js";
export * from "./gateways/client/requests/index.js";
export * from "./idling/client/requests/index.js";
export * from "./issues/client/requests/index.js";
export * from "./liveShares/client/requests/index.js";
export * from "./readings/client/requests/index.js";
export * from "./speedingIntervals/client/requests/index.js";
export * from "./tags/client/requests/index.js";
export * from "./trainingAssignments/client/requests/index.js";
export * from "./trainingCourses/client/requests/index.js";
export * from "./trips/client/requests/index.js";
export * from "./userRoles/client/requests/index.js";
export * from "./users/client/requests/index.js";
export * from "./v1Messages/client/requests/index.js";
export * from "./webhooks/client/requests/index.js";
