export * from "./addresses/client/requests/index.js";
export * as addresses from "./addresses/index.js";
export * from "./alerts/client/requests/index.js";
export * as alerts from "./alerts/index.js";
export * from "./alerts/types/index.js";
export * from "./assets/client/requests/index.js";
export * as assets from "./assets/index.js";
export * from "./assets/types/index.js";
export * from "./attributes/client/requests/index.js";
export * as attributes from "./attributes/index.js";
export * from "./attributes/types/index.js";
export * from "./authTokenForDriver/client/requests/index.js";
export * as authTokenForDriver from "./authTokenForDriver/index.js";
export * from "./betaApIs/client/requests/index.js";
export * as betaApIs from "./betaApIs/index.js";
export * from "./betaApIs/types/index.js";
export * from "./carrierProposedAssignments/client/requests/index.js";
export * as carrierProposedAssignments from "./carrierProposedAssignments/index.js";
export * from "./coaching/client/requests/index.js";
export * as coaching from "./coaching/index.js";
export * from "./contacts/client/requests/index.js";
export * as contacts from "./contacts/index.js";
export * from "./documents/client/requests/index.js";
export * as documents from "./documents/index.js";
export * from "./driverQrCodes/client/requests/index.js";
export * as driverQrCodes from "./driverQrCodes/index.js";
export * from "./drivers/client/requests/index.js";
export * as drivers from "./drivers/index.js";
export * from "./drivers/types/index.js";
export * from "./driverTrailerAssignments/client/requests/index.js";
export * as driverTrailerAssignments from "./driverTrailerAssignments/index.js";
export * from "./driverVehicleAssignments/client/requests/index.js";
export * as driverVehicleAssignments from "./driverVehicleAssignments/index.js";
export * from "./driverVehicleAssignments/types/index.js";
export * from "./equipment/client/requests/index.js";
export * as equipment from "./equipment/index.js";
export * from "./equipment/types/index.js";
export * as fleet from "./fleet/index.js";
export * from "./forms/client/requests/index.js";
export * as forms from "./forms/index.js";
export * from "./fuelAndEnergy/client/requests/index.js";
export * as fuelAndEnergy from "./fuelAndEnergy/index.js";
export * from "./fuelAndEnergy/types/index.js";
export * from "./gateways/client/requests/index.js";
export * as gateways from "./gateways/index.js";
export * from "./hoursOfService/client/requests/index.js";
export * as hoursOfService from "./hoursOfService/index.js";
export * from "./hoursOfService/types/index.js";
export * from "./hubs/client/requests/index.js";
export * as hubs from "./hubs/index.js";
export * from "./idling/client/requests/index.js";
export * as idling from "./idling/index.js";
export * from "./idling/types/index.js";
export * from "./ifta/client/requests/index.js";
export * as ifta from "./ifta/index.js";
export * from "./ifta/types/index.js";
export * from "./industrial/client/requests/index.js";
export * as industrial from "./industrial/index.js";
export * from "./issues/client/requests/index.js";
export * as issues from "./issues/index.js";
export * as legacy from "./legacy/index.js";
export * from "./legacyApIs/client/requests/index.js";
export * as legacyApIs from "./legacyApIs/index.js";
export * from "./legacyApIs/types/index.js";
export * from "./liveSharingLinks/client/requests/index.js";
export * as liveSharingLinks from "./liveSharingLinks/index.js";
export * from "./liveSharingLinks/types/index.js";
export * from "./locationAndSpeed/client/requests/index.js";
export * as locationAndSpeed from "./locationAndSpeed/index.js";
export * from "./maintenance/client/requests/index.js";
export * as maintenance from "./maintenance/index.js";
export * from "./media/client/requests/index.js";
export * as media from "./media/index.js";
export * from "./media/types/index.js";
export * from "./messages/client/requests/index.js";
export * as messages from "./messages/index.js";
export * as organizationInfo from "./organizationInfo/index.js";
export * from "./plans/client/requests/index.js";
export * as plans from "./plans/index.js";
export * from "./previewApIs/client/requests/index.js";
export * as previewApIs from "./previewApIs/index.js";
export * from "./routeEvents/client/requests/index.js";
export * as routeEvents from "./routeEvents/index.js";
export * from "./routes/client/requests/index.js";
export * as routes from "./routes/index.js";
export * from "./routes/types/index.js";
export * from "./safety/client/requests/index.js";
export * as safety from "./safety/index.js";
export * from "./safety/types/index.js";
export * from "./sensors/client/requests/index.js";
export * as sensors from "./sensors/index.js";
export * from "./settings/client/requests/index.js";
export * as settings from "./settings/index.js";
export * from "./speedingIntervals/client/requests/index.js";
export * as speedingIntervals from "./speedingIntervals/index.js";
export * from "./speedingIntervals/types/index.js";
export * from "./tachographEuOnly/client/requests/index.js";
export * as tachographEuOnly from "./tachographEuOnly/index.js";
export * from "./tags/client/requests/index.js";
export * as tags from "./tags/index.js";
export * from "./trailerAssignments/client/requests/index.js";
export * as trailerAssignments from "./trailerAssignments/index.js";
export * from "./trailers/client/requests/index.js";
export * as trailers from "./trailers/index.js";
export * from "./trainingAssignments/client/requests/index.js";
export * as trainingAssignments from "./trainingAssignments/index.js";
export * from "./trainingCourses/client/requests/index.js";
export * as trainingCourses from "./trainingCourses/index.js";
export * from "./trips/client/requests/index.js";
export * as trips from "./trips/index.js";
export * from "./trips/types/index.js";
export * from "./users/client/requests/index.js";
export * as users from "./users/index.js";
export * from "./vehicleLocations/client/requests/index.js";
export * as vehicleLocations from "./vehicleLocations/index.js";
export * from "./vehicleStats/client/requests/index.js";
export * as vehicleStats from "./vehicleStats/index.js";
export * from "./vehicleStats/types/index.js";
export * from "./vehicles/client/requests/index.js";
export * as vehicles from "./vehicles/index.js";
export * from "./webhooks/client/requests/index.js";
export * as webhooks from "./webhooks/index.js";
export * from "./workOrders/client/requests/index.js";
export * as workOrders from "./workOrders/index.js";
export * from "./workOrders/types/index.js";
