/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         documentId: "6c8c0c01-206a-41a4-9d21-15b9978d04cb"
 *     }
 */
export interface DocumentPdfGenerationRequest {
    /** ID of the document. */
    documentId: string;
}
