/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Webhook-123",
 *         url: "https://www.Webhook-123.com/webhook/listener"
 *     }
 */
export interface WebhooksPostWebhooksRequestBody {
    /** The list of custom headers that users can include with their request */
    customHeaders?: Samsara.CustomHeadersObjectRequestBody[];
    /** [beta] The list of event types associated with a particular event type */
    eventTypes?: WebhooksPostWebhooksRequestBody.EventTypes.Item[];
    /** The  name of the webhook. This will appear in both Samsara’s cloud dashboard and the API. It can be set or updated through the Samsara Dashboard or through the API at any time. */
    name: string;
    /** The url of the webhook. This will appear in both Samsara’s cloud dashboard and the API. It can be set or updated through the Samsara Dashboard or through the API at any time. */
    url: string;
    /** The version of the webhook.  Valid values: `2018-01-01`, `2021-06-09`, `2022-09-13`, `2024-02-27` */
    version?: WebhooksPostWebhooksRequestBody.Version;
}

export namespace WebhooksPostWebhooksRequestBody {
    export type EventTypes = EventTypes.Item[];

    export namespace EventTypes {
        /**
         * event type name  Valid values: `AddressCreated`, `AddressDeleted`, `AddressUpdated`, `AlertIncident`, `AlertObjectEvent`, `DocumentSubmitted`, `DriverCreated`, `DriverUpdated`, `DvirSubmitted`, `EngineFaultOff`, `EngineFaultOn`, `FormSubmitted`, `FormUpdated`, `GatewayUnplugged`, `GeofenceEntry`, `GeofenceExit`, `IssueCreated`, `PredictiveMaintenanceAlert`, `RouteStopArrival`, `RouteStopDeparture`, `RouteStopResequence`, `SevereSpeedingEnded`, `SevereSpeedingStarted`, `SuddenFuelLevelDrop`, `SuddenFuelLevelRise`, `VehicleCreated`, `VehicleUpdated`
         */
        export type Item =
            | "AddressCreated"
            | "AddressDeleted"
            | "AddressUpdated"
            | "AlertIncident"
            | "AlertObjectEvent"
            | "DocumentSubmitted"
            | "DriverCreated"
            | "DriverUpdated"
            | "DvirSubmitted"
            | "EngineFaultOff"
            | "EngineFaultOn"
            | "FormSubmitted"
            | "FormUpdated"
            | "GatewayUnplugged"
            | "GeofenceEntry"
            | "GeofenceExit"
            | "IssueCreated"
            | "PredictiveMaintenanceAlert"
            | "RouteStopArrival"
            | "RouteStopDeparture"
            | "RouteStopResequence"
            | "SevereSpeedingEnded"
            | "SevereSpeedingStarted"
            | "SuddenFuelLevelDrop"
            | "SuddenFuelLevelRise"
            | "VehicleCreated"
            | "VehicleUpdated";
        export const Item = {
            AddressCreated: "AddressCreated",
            AddressDeleted: "AddressDeleted",
            AddressUpdated: "AddressUpdated",
            AlertIncident: "AlertIncident",
            AlertObjectEvent: "AlertObjectEvent",
            DocumentSubmitted: "DocumentSubmitted",
            DriverCreated: "DriverCreated",
            DriverUpdated: "DriverUpdated",
            DvirSubmitted: "DvirSubmitted",
            EngineFaultOff: "EngineFaultOff",
            EngineFaultOn: "EngineFaultOn",
            FormSubmitted: "FormSubmitted",
            FormUpdated: "FormUpdated",
            GatewayUnplugged: "GatewayUnplugged",
            GeofenceEntry: "GeofenceEntry",
            GeofenceExit: "GeofenceExit",
            IssueCreated: "IssueCreated",
            PredictiveMaintenanceAlert: "PredictiveMaintenanceAlert",
            RouteStopArrival: "RouteStopArrival",
            RouteStopDeparture: "RouteStopDeparture",
            RouteStopResequence: "RouteStopResequence",
            SevereSpeedingEnded: "SevereSpeedingEnded",
            SevereSpeedingStarted: "SevereSpeedingStarted",
            SuddenFuelLevelDrop: "SuddenFuelLevelDrop",
            SuddenFuelLevelRise: "SuddenFuelLevelRise",
            VehicleCreated: "VehicleCreated",
            VehicleUpdated: "VehicleUpdated",
        } as const;
    }

    /**
     * The version of the webhook.  Valid values: `2018-01-01`, `2021-06-09`, `2022-09-13`, `2024-02-27`
     */
    export type Version = "2018-01-01" | "2021-06-09" | "2022-09-13" | "2024-02-27";
    export const Version = {
        TwoThousandEighteen0101: "2018-01-01",
        TwoThousandTwentyOne0609: "2021-06-09",
        TwoThousandTwentyTwo0913: "2022-09-13",
        TwoThousandTwentyFour0227: "2024-02-27",
    } as const;
}
