/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool.js";
import { SamsaraClient } from "../../../src/Client";

describe("Configurations", () => {
    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({ token: "test", version: "2025-05-12", environment: server.baseUrl });
        const rawRequestBody = {
            actions: [{ actionTypeId: 1 }],
            isEnabled: true,
            name: "My Harsh Event Alert",
            scope: { all: true },
            triggers: [{ triggerTypeId: 1000 }],
        };
        const rawResponseBody = {
            data: {
                actions: [{ actionTypeId: 1 }],
                createdAtTime: "2019-06-13T19:08:25Z",
                externalIds: { key: "value" },
                id: "e1c5dffc-c7b7-47b0-a778-6a65de638abf",
                isEnabled: true,
                lastModifiedAtTime: "2019-06-13T19:08:25Z",
                name: "My Harsh Event Alert",
                operationalSettings: {
                    timeRangeType: "activeBetween",
                    timeRanges: [
                        {
                            daysOfWeek: ["SATURDAY", "TUESDAY", "SUNDAY"],
                            endTime: "20:00",
                            startTime: "11:00",
                            timezone: "America/Los_Angeles",
                        },
                    ],
                },
                scope: {
                    all: true,
                    assets: [{ assetId: "12443", assetType: "uncategorized" }],
                    drivers: [{ driverId: "12434" }],
                    tags: [{ id: "3914", name: "East Coast", parentTagId: "4815" }],
                    widgets: [{ widgetId: "12434" }],
                },
                triggers: [{ triggerTypeId: 1000 }],
            },
        };
        server
            .mockEndpoint()
            .post("/alerts/configurations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.alerts.configurations.create({
            actions: [
                {
                    actionTypeId: 1,
                },
            ],
            isEnabled: true,
            name: "My Harsh Event Alert",
            scope: {
                all: true,
            },
            triggers: [
                {
                    triggerTypeId: 1000,
                },
            ],
        });
        expect(response).toEqual({
            data: {
                actions: [
                    {
                        actionTypeId: 1,
                    },
                ],
                createdAtTime: "2019-06-13T19:08:25Z",
                externalIds: {
                    key: "value",
                },
                id: "e1c5dffc-c7b7-47b0-a778-6a65de638abf",
                isEnabled: true,
                lastModifiedAtTime: "2019-06-13T19:08:25Z",
                name: "My Harsh Event Alert",
                operationalSettings: {
                    timeRangeType: "activeBetween",
                    timeRanges: [
                        {
                            daysOfWeek: ["SATURDAY", "TUESDAY", "SUNDAY"],
                            endTime: "20:00",
                            startTime: "11:00",
                            timezone: "America/Los_Angeles",
                        },
                    ],
                },
                scope: {
                    all: true,
                    assets: [
                        {
                            assetId: "12443",
                            assetType: "uncategorized",
                        },
                    ],
                    drivers: [
                        {
                            driverId: "12434",
                        },
                    ],
                    tags: [
                        {
                            id: "3914",
                            name: "East Coast",
                            parentTagId: "4815",
                        },
                    ],
                    widgets: [
                        {
                            widgetId: "12434",
                        },
                    ],
                },
                triggers: [
                    {
                        triggerTypeId: 1000,
                    },
                ],
            },
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({ token: "test", version: "2025-05-12", environment: server.baseUrl });

        server.mockEndpoint().delete("/alerts/configurations").respondWith().statusCode(200).build();

        const response = await client.alerts.configurations.delete({
            id: "id",
        });
        expect(response).toEqual(undefined);
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({ token: "test", version: "2025-05-12", environment: server.baseUrl });
        const rawRequestBody = { id: "e1c5dffc-c7b7-47b0-a778-6a65de638abf" };
        const rawResponseBody = {
            data: {
                actions: [{ actionTypeId: 1 }],
                createdAtTime: "2019-06-13T19:08:25Z",
                externalIds: { key: "value" },
                id: "e1c5dffc-c7b7-47b0-a778-6a65de638abf",
                isEnabled: true,
                lastModifiedAtTime: "2019-06-13T19:08:25Z",
                name: "My Harsh Event Alert",
                operationalSettings: {
                    timeRangeType: "activeBetween",
                    timeRanges: [
                        {
                            daysOfWeek: ["SATURDAY", "TUESDAY", "SUNDAY"],
                            endTime: "20:00",
                            startTime: "11:00",
                            timezone: "America/Los_Angeles",
                        },
                    ],
                },
                scope: {
                    all: true,
                    assets: [{ assetId: "12443", assetType: "uncategorized" }],
                    drivers: [{ driverId: "12434" }],
                    tags: [{ id: "3914", name: "East Coast", parentTagId: "4815" }],
                    widgets: [{ widgetId: "12434" }],
                },
                triggers: [{ triggerTypeId: 1000 }],
            },
        };
        server
            .mockEndpoint()
            .patch("/alerts/configurations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.alerts.configurations.update({
            id: "e1c5dffc-c7b7-47b0-a778-6a65de638abf",
        });
        expect(response).toEqual({
            data: {
                actions: [
                    {
                        actionTypeId: 1,
                    },
                ],
                createdAtTime: "2019-06-13T19:08:25Z",
                externalIds: {
                    key: "value",
                },
                id: "e1c5dffc-c7b7-47b0-a778-6a65de638abf",
                isEnabled: true,
                lastModifiedAtTime: "2019-06-13T19:08:25Z",
                name: "My Harsh Event Alert",
                operationalSettings: {
                    timeRangeType: "activeBetween",
                    timeRanges: [
                        {
                            daysOfWeek: ["SATURDAY", "TUESDAY", "SUNDAY"],
                            endTime: "20:00",
                            startTime: "11:00",
                            timezone: "America/Los_Angeles",
                        },
                    ],
                },
                scope: {
                    all: true,
                    assets: [
                        {
                            assetId: "12443",
                            assetType: "uncategorized",
                        },
                    ],
                    drivers: [
                        {
                            driverId: "12434",
                        },
                    ],
                    tags: [
                        {
                            id: "3914",
                            name: "East Coast",
                            parentTagId: "4815",
                        },
                    ],
                    widgets: [
                        {
                            widgetId: "12434",
                        },
                    ],
                },
                triggers: [
                    {
                        triggerTypeId: 1000,
                    },
                ],
            },
        });
    });
});
