// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteIndustrialAssetRequest {
    /** Id of the asset to be deleted. */
    id: string;
}
