/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ConfigurationsDeleteRequest {
    /**
     * The unqiue Samsara id of the alert configuration.
     */
    id: string;
}
