/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IdlingListRequestPtoState = "active" | "inactive";
export const IdlingListRequestPtoState = {
    Active: "active",
    Inactive: "inactive",
} as const;
