// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         timestamp: 1000000
 *     }
 */
export interface V1GetVehicleHarshEventRequest {
    /** Timestamp in milliseconds representing the timestamp of a harsh event. */
    timestamp: number;
}
