// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         operator: "provider",
 *         providerDataPackages: ["all", "maintenance", "maintenance", "maintenance"],
 *         recipientDataPackages: ["all", "reefer", "all", "maintenance"],
 *         recipientOrganizationId: "456",
 *         recipientOrganizationName: "Acme Logistics"
 *     }
 */
export interface AssetSharingAgreementsCreateAssetSharingAgreementRequestBody {
    /** Defines where the gateways will be located.  Valid values: `provider`, `recipient` */
    operator: AssetSharingAgreementsCreateAssetSharingAgreementRequestBody.Operator;
    /** List of data packages the provider will see. */
    providerDataPackages: AssetSharingAgreementsCreateAssetSharingAgreementRequestBody.ProviderDataPackages.Item[];
    /** List of data packages the recipient will see. */
    recipientDataPackages: AssetSharingAgreementsCreateAssetSharingAgreementRequestBody.RecipientDataPackages.Item[];
    /** The ID of the recipient organization. */
    recipientOrganizationId: string;
    /** The display name to use for the recipient organization. */
    recipientOrganizationName: string;
}

export namespace AssetSharingAgreementsCreateAssetSharingAgreementRequestBody {
    /** Defines where the gateways will be located.  Valid values: `provider`, `recipient` */
    export const Operator = {
        Provider: "provider",
        Recipient: "recipient",
    } as const;
    export type Operator = (typeof Operator)[keyof typeof Operator];
    export type ProviderDataPackages = ProviderDataPackages.Item[];

    export namespace ProviderDataPackages {
        /** Data package type  Valid values: `safety`, `telematics`, `location`, `maintenance`, `reefer`, `all` */
        export const Item = {
            Safety: "safety",
            Telematics: "telematics",
            Location: "location",
            Maintenance: "maintenance",
            Reefer: "reefer",
            All: "all",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    export type RecipientDataPackages = RecipientDataPackages.Item[];

    export namespace RecipientDataPackages {
        /** Data package type  Valid values: `safety`, `telematics`, `location`, `maintenance`, `reefer`, `all` */
        export const Item = {
            Safety: "safety",
            Telematics: "telematics",
            Location: "location",
            Maintenance: "maintenance",
            Reefer: "reefer",
            All: "all",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
