// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         assetId: "281474978683353"
 *     }
 */
export interface AssetAssignmentsUnassignAssetAssignmentRequestBody {
    /** Samsara ID of the asset. */
    assetId: string;
}
