// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteVendorGroupRequest {
    /** Unique identifier for the VendorProfile record. */
    id: string;
}
