// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         missing_reason: "MISPLACED",
 *         recovery_status: "YES",
 *         status: "RECOVERED"
 *     }
 */
export interface DeviceRecoveryRecoverAssetRequestBody {
    /** The ID of the asset. This can be a Samsara internal ID or an external ID in the format `key:value`. */
    id: string;
    /** Optional additional details about the recovery. */
    additional_details?: string;
    /** The reason the asset was marked as missing.  Valid values: `MISPLACED`, `STOLEN`, `NOT_SURE` */
    missing_reason: DeviceRecoveryRecoverAssetRequestBody.MissingReason;
    /** Whether the asset has been physically recovered.  Valid values: `YES`, `NO`, `NOT_SURE` */
    recovery_status: DeviceRecoveryRecoverAssetRequestBody.RecoveryStatus;
    /** The recovery status to set for the asset.  Valid values: `RECOVERED` */
    status: DeviceRecoveryRecoverAssetRequestBody.Status;
}

export namespace DeviceRecoveryRecoverAssetRequestBody {
    /** The reason the asset was marked as missing.  Valid values: `MISPLACED`, `STOLEN`, `NOT_SURE` */
    export const MissingReason = {
        Misplaced: "MISPLACED",
        Stolen: "STOLEN",
        NotSure: "NOT_SURE",
    } as const;
    export type MissingReason = (typeof MissingReason)[keyof typeof MissingReason];
    /** Whether the asset has been physically recovered.  Valid values: `YES`, `NO`, `NOT_SURE` */
    export const RecoveryStatus = {
        Yes: "YES",
        No: "NO",
        NotSure: "NOT_SURE",
    } as const;
    export type RecoveryStatus = (typeof RecoveryStatus)[keyof typeof RecoveryStatus];
    /** The recovery status to set for the asset.  Valid values: `RECOVERED` */
    export const Status = {
        Recovered: "RECOVERED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
