// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../../../../index.js";

/**
 * @example
 *     {
 *         orderStatus: "Unknown",
 *         vendorId: "281474976710656"
 *     }
 */
export interface EntityPurchaseOrdersServiceCreatePurchaseOrderRequestBody {
    /** General ledger code associated with this purchase order. */
    glCode?: string;
    /** Vendor invoice number associated with this purchase order. */
    invoiceNumber?: string;
    /** Free-text notes for the purchase order. */
    notes?: string;
    /** Current customer-visible status of the purchase order.  Valid values: `Unknown`, `Draft`, `Open`, `InReview`, `Approved`, `Rejected`, `SentToVendor`, `PartiallyReceived`, `FullyReceived`, `Returned`, `Cancelled`, `Closed` */
    orderStatus: EntityPurchaseOrdersServiceCreatePurchaseOrderRequestBody.OrderStatus;
    otherCost?: Samsara.CreatePurchaseOrderEntityPurchaseOrderMoneyInputPublicVariantc9366B66E6FcTypeRequestBody;
    /** Parts ordered on the purchase order. */
    parts?: Samsara.CreatePurchaseOrderEntityPurchaseOrderPurchaseOrderPartInputPublicVariantfe4658938A0FTypeRequestBody[];
    /** Optional prefix included in the purchase order number. */
    poNumberPrefix?: string;
    /** Optional suffix included in the purchase order number. */
    poNumberSuffix?: string;
    tax?: Samsara.CreatePurchaseOrderEntityPurchaseOrderTaxAdjustmentInputTypeRequestBody;
    /** Shipment tracking number for the purchase order. */
    trackingNumber?: string;
    /** ID of the vendor supplying this purchase order. */
    vendorId: string;
}

export namespace EntityPurchaseOrdersServiceCreatePurchaseOrderRequestBody {
    /** Current customer-visible status of the purchase order.  Valid values: `Unknown`, `Draft`, `Open`, `InReview`, `Approved`, `Rejected`, `SentToVendor`, `PartiallyReceived`, `FullyReceived`, `Returned`, `Cancelled`, `Closed` */
    export const OrderStatus = {
        Unknown: "Unknown",
        Draft: "Draft",
        Open: "Open",
        InReview: "InReview",
        Approved: "Approved",
        Rejected: "Rejected",
        SentToVendor: "SentToVendor",
        PartiallyReceived: "PartiallyReceived",
        FullyReceived: "FullyReceived",
        Returned: "Returned",
        Cancelled: "Cancelled",
        Closed: "Closed",
    } as const;
    export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];
}
