// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface EntityUpcomingPreventativeMaintenancesServiceUpdateUpcomingPreventiveMaintenanceRequestBody {
    /** Samsara ID for the asset. */
    assetId?: string;
    /** ID of the preventive maintenance schedule that the vehicle is scheduled to be serviced for. */
    scheduleId?: string;
    /** Date and time when the prior instance was resolved. */
    lastResolvedAt?: string;
    /** Engine hours at the time the prior instance was resolved. */
    lastResolvedAtEngineHours?: number;
    /** Odometer reading at the time the prior instance was resolved. Measured in meters. */
    lastResolvedAtOdometer?: number;
    /** The next engine hour value that the vehicle is scheduled to be serviced. */
    nextEngineHours?: number;
    /** The next odometer value that the vehicle is scheduled to be serviced. Measured in meters. */
    nextOdometer?: number;
    /** The next time that the vehicle is scheduled to be serviced for a date based PM. */
    nextTime?: string;
}
