// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         correlationId: "correlationId"
 *     }
 */
export interface GetFunctionRunRequest {
    /** The name of the Function. */
    name: string;
    /** The unique correlationId of the Function run, returned by the start run endpoint. */
    correlationId: string;
}
