// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         startTime: "startTime"
 *     }
 */
export interface GetVoiceSessionsStreamRequest {
    /** Lower bound on session start time, in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2026-05-19T14:23:11Z, 2026-05-19T14:23:11.455Z, OR 2026-05-19T10:23:11-04:00). */
    startTime: string;
    /** Upper bound on session start time, in RFC 3339 format. Defaults to the current time when omitted. Millisecond precision and timezones are supported. */
    endTime?: string;
    /** Required, comma-separated list of Agent Studio agent IDs to filter sessions on. Up to 100 agent IDs per call. */
    agentIds?: string | string[];
    /** Optional, comma-separated list of vehicle IDs. When set, only sessions whose target device was associated with one of these vehicles are returned. Up to 100 vehicle IDs per call. */
    vehicleIds?: string | string[];
    /** Optional, comma-separated list of driver IDs. When set, only sessions whose target device was associated with one of these drivers are returned. Up to 100 driver IDs per call. */
    driverIds?: string | string[];
    /** Optional, comma-separated list of session statuses to filter on. Valid values: `completed`, `running`, `failed`, `unknown`. Defaults to `completed` when omitted. */
    sessionStatus?: string | string[];
    /**  If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results. */
    after?: string;
    /** Maximum number of sessions to return. Default 50, max 100. */
    limit?: number;
}
