// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../../../../index.js";

/**
 * @example
 *     {
 *         placeId: 1000000
 *     }
 */
export interface PlacesPatchPlaceRequestBody {
    /** Samsara place id to update (required). Do not send `externalId` in the same request. */
    placeId: number;
    /** External id token in `key:value` form (e.g. crmId:warehouse-east). Mutually exclusive with `placeId`. Batch lookup by external id is not implemented for this endpoint yet; callers should use `placeId` until supported. */
    externalId?: string;
    /** Single-line address string. */
    address?: string;
    /** Camera recording mode: fullRecording, driverPrivacy, completePrivacy, or inherit.  Valid values: `fullRecording`, `driverPrivacy`, `completePrivacy`, `inherit`, `unknown`, `unspecified` */
    cameraRecordingModeType?: PlacesPatchPlaceRequestBody.CameraRecordingModeType;
    /** When present, replaces external ids for the place. */
    externalIds?: PlacesPatchPlaceRequestBody.ExternalIds;
    /** Polygon vertices; at least three when switching to polygon mode. */
    geofence?: Samsara.GeofenceVertexInputRequestBody[];
    hubLocations?: Samsara.PatchPlaceHubLocationsBodyRequestBody;
    /** When present, replaces IFTA exemption types for the place. */
    iftaExemptionTypes?: string[];
    /** Center latitude when switching to or editing a circle geofence. */
    latitude?: number;
    /** Center longitude when switching to or editing a circle geofence. */
    longitude?: number;
    /** Place name. */
    name?: string;
    navigation?: Samsara.PostPlaceNavigationInputRequestBody;
    /** Notes. */
    notes?: string;
    /** Unsupported on patch; when provided this API returns InvalidArgument. */
    placeTypes?: string[];
    /** Circle radius in meters; use with latitude and longitude. */
    radiusMeters?: number;
    /** When present, replaces safety event exclusions for the place. */
    safetyEventExclusions?: string[];
    streetView?: Samsara.PlaceStreetViewResponseRequestBody;
    /** When present, replaces all tag associations for the place. */
    tags?: Samsara.PostPlaceTagRefRequestBody[];
}

export namespace PlacesPatchPlaceRequestBody {
    /** Camera recording mode: fullRecording, driverPrivacy, completePrivacy, or inherit.  Valid values: `fullRecording`, `driverPrivacy`, `completePrivacy`, `inherit`, `unknown`, `unspecified` */
    export const CameraRecordingModeType = {
        FullRecording: "fullRecording",
        DriverPrivacy: "driverPrivacy",
        CompletePrivacy: "completePrivacy",
        Inherit: "inherit",
        Unknown: "unknown",
        Unspecified: "unspecified",
    } as const;
    export type CameraRecordingModeType = (typeof CameraRecordingModeType)[keyof typeof CameraRecordingModeType];

    /**
     * When present, replaces external ids for the place.
     */
    export type ExternalIds = {};
}
