// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7"
 *     }
 */
export interface QualificationsArchiveQualificationRecordRequestBody {
    /** ID of the qualification record to archive. */
    id: string;
}
