/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VehicleListRequestQuarter = "Q1" | "Q2" | "Q3" | "Q4";
export const VehicleListRequestQuarter = {
    Q1: "Q1",
    Q2: "Q2",
    Q3: "Q3",
    Q4: "Q4",
} as const;
