/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type HosDailyLogsRequestDriverActivationStatus = "active" | "deactivated";
export const HosDailyLogsRequestDriverActivationStatus = {
    Active: "active",
    Deactivated: "deactivated",
} as const;
