/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import { Tokens } from "../resources/tokens/client/Client.js";

export declare namespace Auth {
    export interface Options {
        environment?: core.Supplier<environments.SamsaraEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the X-Samsara-Version header */
        version?: "2025-05-12";
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Auth {
    protected readonly _options: Auth.Options;
    protected _tokens: Tokens | undefined;

    constructor(_options: Auth.Options = {}) {
        this._options = _options;
    }

    public get tokens(): Tokens {
        return (this._tokens ??= new Tokens(this._options));
    }
}
