// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetHosLogsRequest {
    /** A filter on the data based on this comma-separated list of tag IDs. Example: `tagIds=1234,5678` */
    tagIds?: string | string[];
    /** A filter on the data based on this comma-separated list of parent tag IDs, for use by orgs with tag hierarchies. Specifying a parent tag will implicitly include all descendent tags of the parent tag. Example: `parentTagIds=345,678` */
    parentTagIds?: string | string[];
    /** A filter on the data based on this comma-separated list of driver IDs. Example: `driverIds=1234,5678` */
    driverIds?: string | string[];
    /** A start time in RFC 3339 format. Defaults to now if not provided. Millisecond precision and timezones are supported. (Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00). */
    startTime?: string;
    /** An end time in RFC 3339 format. Defaults to now if not provided. Millisecond precision and timezones are supported. (Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00). */
    endTime?: string;
    /** If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results. */
    after?: string;
}
