// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Action to take.
 */
export interface ActionObjectRequestBody {
    actionParams?: Samsara.ActionParamsObjectRequestBody;
    /**
     * The id of the of the action type. Reference the following list for the ids:
     * The following action types are in Beta:
     * Driver App Push = 5
     * The following action types are Stable:
     * Notification (Email, Text, Samsara Fleet Push) = 1
     * Dashboard Notification = 3
     * Webhook = 4
     * Slack = 6
     */
    actionTypeId: number;
}
