// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * An Address object.
 */
export interface Address {
    /** Reporting location type associated with the address (used for ELD reporting purposes). Valid values: `yard`, `shortHaul`, `workforceSite`, `riskZone`, `industrialSite`, `alertsOnly`, `agricultureSource`, `avoidanceZone`, `knownGPSJammingZone`, `authorizedZone`, `unauthorizedZone`, `vendor`, `inventory`. */
    addressTypes?: Address.AddressTypes.Item[] | undefined;
    /** An array Contact mini-objects that are associated the Address. */
    contacts?: Samsara.ContactTinyResponse[] | undefined;
    /** The date and time this address was created in RFC 3339 format. */
    createdAtTime?: string | undefined;
    /** The [external IDs](https://developers.samsara.com/docs/external-ids) for the given object. */
    externalIds?: Address.ExternalIds | undefined;
    /** The full street address for this address/geofence, as it might be recognized by Google Maps. */
    formattedAddress: string;
    geofence: Samsara.AddressGeofence;
    /** ID of the Address. */
    id: string;
    /** Latitude of the address. Will be geocoded from `formattedAddress` if not provided. */
    latitude?: number | undefined;
    /** Longitude of the address. Will be geocoded from `formattedAddress` if not provided. */
    longitude?: number | undefined;
    /** Name of the address. */
    name: string;
    /** Notes about the address. */
    notes?: string | undefined;
    /** An array of all tag mini-objects that are associated with the given address entry. */
    tags?: Samsara.TagTinyResponse[] | undefined;
}

export namespace Address {
    export type AddressTypes = AddressTypes.Item[];

    export namespace AddressTypes {
        export const Item = {
            Yard: "yard",
            ShortHaul: "shortHaul",
            WorkforceSite: "workforceSite",
            RiskZone: "riskZone",
            IndustrialSite: "industrialSite",
            AlertsOnly: "alertsOnly",
            AgricultureSource: "agricultureSource",
            AvoidanceZone: "avoidanceZone",
            KnownGpsJammingZone: "knownGPSJammingZone",
            AuthorizedZone: "authorizedZone",
            UnauthorizedZone: "unauthorizedZone",
            Vendor: "vendor",
            Inventory: "inventory",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /**
     * The [external IDs](https://developers.samsara.com/docs/external-ids) for the given object.
     */
    export type ExternalIds = {};
}
