/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

export interface AdvancedIdlingGetIdlingEventsResponseBody {
    /** List of idling event objects. */
    data: SamsaraApi.IdlingEventObjectResponseBody[];
    pagination: SamsaraApi.GoaPaginationResponseResponseBody;
}
