// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * A camera device associated with the alert
 */
export interface AlertObjectWorkforceCameraDeviceResponseBody {
    /** The ID of the camera device associated with the alert */
    id: string;
    /** The name of the camera device */
    name?: string | undefined;
    /** The list of sites associated with the camera device. */
    sites?: Samsara.AlertObjectSitesResponseBody[] | undefined;
    /** The list of [tags](https://kb.samsara.com/hc/en-us/articles/360026674631-Using-Tags-and-Tag-Nesting) associated with the camera device. */
    tags?: Samsara.GoaTagTinyResponseResponseBody[] | undefined;
}
