/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * The vehicle associated with the alert.
 */
export interface AlertObjectVehicleResponseBody {
    /** List of attributes associated with the entity */
    attributes?: SamsaraApi.GoaAttributeTinyResponseBody[];
    /** A map of external ids */
    externalIds?: Record<string, string>;
    /** The ID of the vehicle. */
    id: string;
    /** The name of the vehicle. */
    name?: string;
    /** The serial number of the gateway installed on the asset. */
    serial: string;
    staticAssignedDriver?: SamsaraApi.DriverObjectResponseBody;
    /** The list of [tags](https://kb.samsara.com/hc/en-us/articles/360026674631-Using-Tags-and-Tag-Nesting) associated with the vehicle. */
    tags?: SamsaraApi.GoaTagTinyResponseResponseBody[];
}
