// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface AssetReeferAlarmsStatObjectResponseBody {
    /** All alarms that were reported at the time. */
    alarms?: Samsara.AssetReeferAlarmObjectResponseBody[] | undefined;
    /** Timestamp when the alarms were reported, in Unix milliseconds since epoch */
    changedAtMs?: number | undefined;
}
