// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface AssetSharingAgreementsListSharedAssetsResponseBody {
    /** List of shared assets. */
    data: Samsara.SharedAssetResponseObjectResponseBody[];
    pagination?: Samsara.GoaPaginationResponseResponseBody | undefined;
}
