/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

export interface Attribute {
    /** Denotes the data type of the attribute's values. Valid values: `string`, `number`. */
    attributeType?: Attribute.AttributeType;
    /** Defines whether or not this attribute can be used on the same entity many times (with different values). Valid values: `single`, `multi`. */
    attributeValueQuantity?: Attribute.AttributeValueQuantity;
    /** Denotes the type of entity, driver or asset. Valid values: `driver`, `asset`. */
    entityType?: Attribute.EntityType;
    /** The samsara id of the attribute object. */
    id?: string;
    /** Name of attribute. */
    name?: string;
    /** Number values that can be associated with this attribute */
    numberValues?: number[];
    /** String values that can be associated with this attribute */
    stringValues?: string[];
    /** Representation of values that includes ids. */
    values?: SamsaraApi.AttributeValueTiny[];
}

export namespace Attribute {
    /**
     * Denotes the data type of the attribute's values. Valid values: `string`, `number`.
     */
    export type AttributeType = "string" | "number";
    export const AttributeType = {
        String: "string",
        Number: "number",
    } as const;
    /**
     * Defines whether or not this attribute can be used on the same entity many times (with different values). Valid values: `single`, `multi`.
     */
    export type AttributeValueQuantity = "single" | "multi";
    export const AttributeValueQuantity = {
        Single: "single",
        Multi: "multi",
    } as const;
    /**
     * Denotes the type of entity, driver or asset. Valid values: `driver`, `asset`.
     */
    export type EntityType = "driver" | "asset";
    export const EntityType = {
        Driver: "driver",
        Asset: "asset",
    } as const;
}
