/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Gateway cellular connectivity information.
 */
export interface CellConnectivityResponseResponseBody {
    /** The cellular network provider name. */
    operator?: string;
    /** The cellular signal strength indicator.  Valid values: `1/4`, `2/4`, `3/4`, `4/4`, `unknown` */
    signalBar?: CellConnectivityResponseResponseBody.SignalBar;
}

export namespace CellConnectivityResponseResponseBody {
    /**
     * The cellular signal strength indicator.  Valid values: `1/4`, `2/4`, `3/4`, `4/4`, `unknown`
     */
    export type SignalBar = "1/4" | "2/4" | "3/4" | "4/4" | "unknown";
    export const SignalBar = {
        One4: "1/4",
        Two4: "2/4",
        Three4: "3/4",
        Four4: "4/4",
        Unknown: "unknown",
    } as const;
}
