// This file was auto-generated by Fern from our API Definition.

/**
 * VendorAssetAttributeValue object
 */
export interface CreateVendorGroupEntityVendorProfileVendorAssetAttributeValueInputTypeRequestBody {
    /** ID of a value belonging to the attribute. */
    id: string;
}
