// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * CreatePurchaseOrderEntityPurchaseOrderTaxAdjustment object
 */
export interface CreatePurchaseOrderEntityPurchaseOrderTaxAdjustmentTypeResponseBody {
    /** Tax rate in basis points. Set exactly one of money or basisPoints. */
    basisPoints?: number | undefined;
    money?: Samsara.CreatePurchaseOrderEntityPurchaseOrderMoneyTypeResponseBody | undefined;
}
