// This file was auto-generated by Fern from our API Definition.

/**
 * VendorHourlyMoney object
 */
export interface CreateVendorEntityVendorVendorHourlyMoneyTypeResponseBody {
    /** Nonnegative decimal hourly amount in the organization's currency. */
    amount?: string | undefined;
    /** ISO 4217 currency matching the organization's current currency. */
    currency?: string | undefined;
}
