/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the object that stores the key and the value of the custom headers.
 */
export interface CustomHeadersObjectRequestBody {
    /** The alphanumeric key of the custom header. */
    key: string;
    /** The value of the custom header. The default maximum length of the value is 100 characters. */
    value: string;
}
