// This file was auto-generated by Fern from our API Definition.

/**
 * A minified data input object
 */
export interface DataInputTinyResponse {
    /** Unique identifier for the data input's asset. */
    assetId?: string | undefined;
    /** Data group for this data input. */
    dataGroup?: string | undefined;
    /** Unique identifier for the data input. */
    id?: string | undefined;
    /** Name of this data input. */
    name?: string | undefined;
    /** Units of data for this data input. */
    units?: string | undefined;
}
