// This file was auto-generated by Fern from our API Definition.

/**
 * Defect type data.
 */
export interface DefectTypesResponseDataResponseBody {
    /** Time when defect type was created in RFC 3339 format. */
    createdAtTime: string;
    /** The unique ID of the DVIR defect type. */
    id: string;
    /** DVIR defect type label. */
    label: string;
    /** Section for DVIR defect type.  Valid values: `exteriorFront`, `exteriorRear`, `exteriorSideUnderneath`, `interiorDriverCab`, `interiorPassengerArea`, `other`, `unknown` */
    sectionType: DefectTypesResponseDataResponseBody.SectionType;
    /** The severity of the defect type. Only present for DVIR 2.0 defect types.  Valid values: `major`, `minor`, `notApplicable` */
    severity?: DefectTypesResponseDataResponseBody.Severity | undefined;
}

export namespace DefectTypesResponseDataResponseBody {
    /** Section for DVIR defect type.  Valid values: `exteriorFront`, `exteriorRear`, `exteriorSideUnderneath`, `interiorDriverCab`, `interiorPassengerArea`, `other`, `unknown` */
    export const SectionType = {
        ExteriorFront: "exteriorFront",
        ExteriorRear: "exteriorRear",
        ExteriorSideUnderneath: "exteriorSideUnderneath",
        InteriorDriverCab: "interiorDriverCab",
        InteriorPassengerArea: "interiorPassengerArea",
        Other: "other",
        Unknown: "unknown",
    } as const;
    export type SectionType = (typeof SectionType)[keyof typeof SectionType];
    /** The severity of the defect type. Only present for DVIR 2.0 defect types.  Valid values: `major`, `minor`, `notApplicable` */
    export const Severity = {
        Major: "major",
        Minor: "minor",
        NotApplicable: "notApplicable",
    } as const;
    export type Severity = (typeof Severity)[keyof typeof Severity];
}
