// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * The full recovery state for an asset, including notification recipients and recovery photos.
 */
export interface DeviceRecoveryStateResponseBody {
    /** Additional details provided during recovery. */
    additional_details?: string | undefined;
    /** The unique Samsara ID of the asset. */
    id: string;
    /** The reason the asset was originally marked as missing. */
    missing_reason?: string | undefined;
    /** The human-readable name of the asset. */
    name: string;
    /** A note associated with the recovery state. */
    note?: string | undefined;
    /** Users subscribed to location update notifications for this asset. */
    notification_recipients?: Samsara.NotificationRecipientResponseBody[] | undefined;
    /** Photos associated with the recovery event. URLs are temporary and expire at url_expires_at_ms. */
    recovery_photos?: Samsara.RecoveryPhotoResponseBody[] | undefined;
    /** Whether the asset was physically recovered. */
    recovery_status?: string | undefined;
    /** The current recovery status of the asset.  Valid values: `UNKNOWN`, `MISSING`, `LOCATED`, `RECOVERED` */
    status: DeviceRecoveryStateResponseBody.Status;
    /** Timestamp when the recovery state was last updated, in milliseconds since epoch. */
    updated_at_ms: number;
    /** The ID of the user who last updated the recovery state. */
    updated_by_user_id?: number | undefined;
    /** The unique UUID of this recovery state record. */
    uuid: string;
}

export namespace DeviceRecoveryStateResponseBody {
    /** The current recovery status of the asset.  Valid values: `UNKNOWN`, `MISSING`, `LOCATED`, `RECOVERED` */
    export const Status = {
        Unknown: "UNKNOWN",
        Missing: "MISSING",
        Located: "LOCATED",
        Recovered: "RECOVERED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
