// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface DeviceRecoveryListDeviceRecoveryMissingAssetsResponseBody {
    /** List of assets currently marked as missing. */
    data: Samsara.MissingStateResponseBody[];
    pagination: Samsara.GoaPaginationResponseResponseBody;
}
