/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * A PDF of a document
 */
export interface DocumentPdfQueryResponse {
    data?: SamsaraApi.DocumentPdfQueryResponseData;
}
