/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Locale override (uncommon). These are specified by ISO 3166-2 country codes for supported locales. Valid values: `us`, `at`, `be`, `ca`, `gb`, `fr`, `de`, `ie`, `it`, `lu`, `mx`, `nl`, `es`, `ch`, `pr`.
 */
export type DriverLocale =
    | "us"
    | "at"
    | "be"
    | "ca"
    | "gb"
    | "fr"
    | "de"
    | "ie"
    | "it"
    | "lu"
    | "mx"
    | "nl"
    | "es"
    | "ch"
    | "pr";
export const DriverLocale = {
    Us: "us",
    At: "at",
    Be: "be",
    Ca: "ca",
    Gb: "gb",
    Fr: "fr",
    De: "de",
    Ie: "ie",
    It: "it",
    Lu: "lu",
    Mx: "mx",
    Nl: "nl",
    Es: "es",
    Ch: "ch",
    Pr: "pr",
} as const;
