// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Summary of a driver's efficiency.
 */
export interface DriverEfficiency {
    anticipationBrakeEventCount?: Samsara.AnticipationBrakeEventCount;
    coastingDurationMs?: Samsara.CoastingDurationMs;
    cruiseControlDurationMs?: Samsara.CruiseControlDurationMs;
    driver?: Samsara.ExtendedDriverTinyResponse;
    greenBandDrivingDurationMs?: Samsara.GreenBandDrivingDurationMs;
    highTorqueMs?: Samsara.HighTorqueMs;
    overSpeedMs?: Samsara.OverSpeedMs;
    totalBrakeEventCount?: Samsara.TotalBrakeEventCount;
    totalDistanceDrivenMeters?: Samsara.DistanceDrivenMeters;
    totalDriveTimeDurationMs?: Samsara.DriveTimeDurationMs;
    totalFuelConsumedMl?: Samsara.FuelConsumedMl;
    totalIdleTimeDurationMs?: Samsara.IdleTimeDurationMs;
    totalPowerTakeOffDurationMs?: Samsara.PowerTakeOffDurationMs;
    /** Summaries of vehicle efficiency for each vehicle the driver was driving during the given time period. */
    vehicleSummaries?: Samsara.VehicleSummary[];
}
