/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * Details specific to Driver Recorded.
 */
export interface DriverRecordedResponseBody {
    driver?: SamsaraApi.AlertObjectDriverResponseBody;
    vehicle?: SamsaraApi.AlertObjectVehicleResponseBody;
}
