// This file was auto-generated by Fern from our API Definition.

/**
 * Equipment engine status.
 */
export interface EngineStatusResponseBody {
    /** Boolean value for whether engine is running or not. */
    Running?: boolean | undefined;
    /** Date time in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00). */
    datetime?: string | undefined;
}
