// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * UpcomingPreventativeMaintenance object
 */
export interface EntityListUpcomingPreventiveMaintenanceTypeResponseBody {
    asset?: Samsara.EntityUpcomingPreventativeMaintenanceAssetRefTypeResponseBody | undefined;
    /** Current engine hours for the asset at the time of query. */
    currentEngineHours?: number | undefined;
    /** Current odometer reading for the asset at the time of query. Measured in meters. */
    currentOdometer?: number | undefined;
    /** The number of days until the next scheduled service for a date based PM. */
    dueInDays?: number | undefined;
    /** The number of engine hours until the next scheduled service. */
    dueInEngineHours?: number | undefined;
    /** The odometer distance until the next scheduled service. Measured in meters. */
    dueInOdometer?: number | undefined;
    /** Date and time when the prior instance was resolved. */
    lastResolvedAt?: string | undefined;
    /** Engine hours at the time the prior instance was resolved. */
    lastResolvedAtEngineHours?: number | undefined;
    /** Odometer reading at the time the prior instance was resolved. Measured in meters. */
    lastResolvedAtOdometer?: number | undefined;
    /** The next engine hour value that the vehicle is scheduled to be serviced. */
    nextEngineHours?: number | undefined;
    /** The next odometer value that the vehicle is scheduled to be serviced. Measured in meters. */
    nextOdometer?: number | undefined;
    /** The next time that the vehicle is scheduled to be serviced for a date based PM. */
    nextTime?: string | undefined;
    preventativeMaintenanceSchedule?:
        | Samsara.EntityUpcomingPreventativeMaintenancePreventativeMaintenanceScheduleRefTypeResponseBody
        | undefined;
    /** Status of the preventive maintenance schedule. */
    status?: string | undefined;
    workOrder?: Samsara.EntityUpcomingPreventativeMaintenanceWorkOrderRefTypeResponseBody | undefined;
}
