// This file was auto-generated by Fern from our API Definition.

/**
 * Reference to a Asset
 */
export interface EntityUpdateUpcomingPreventiveMaintenanceAssetRefTypeResponseBody {
    /** The ID of the referenced Asset. */
    id: string;
}
