// This file was auto-generated by Fern from our API Definition.

/**
 * Reference to a PartDefinition
 */
export interface EntityCreatePartInventoryLocationPartDefinitionRefTypeResponseBody {
    /** The ID of the referenced PartDefinition. */
    id: string;
}
