// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * EntityCreateStockMovementStockMovementLocation object
 */
export interface EntityCreateStockMovementStockMovementLocationTypeResponseBody {
    /** Aisle within the location where the part is stored. */
    aisle?: string | undefined;
    /** Quantity available to be consumed at this location after the movement. */
    availableQuantity?: number | undefined;
    /** Bin within the location where the part is stored. */
    bin?: string | undefined;
    /** Time when the inventory level record was created. */
    createdAtTime?: string | undefined;
    /** Total physical quantity on hand at this location after the movement. */
    currentQuantity?: number | undefined;
    /** Unique identifier for the part inventory level record. */
    id?: string | undefined;
    /** Whether costing is tracked at this location. */
    isCostTracked?: boolean | undefined;
    /** Whether the available quantity is greater than zero and at or below the reorder threshold. */
    isLowStock?: boolean | undefined;
    /** Maximum quantity to keep in stock at this location. */
    maxStockLevel?: number | undefined;
    /** Minimum quantity to keep in stock at this location. */
    minStockLevel?: number | undefined;
    /** Unique identifier for the part definition these inventory levels are tracked for. */
    partSamsara?: string | undefined;
    /** Unique identifier for the place linked to the maintenance site holding this inventory. */
    place?: string | undefined;
    /** Quantity to reorder when stock reaches the reorder threshold. */
    reorderQuantity?: number | undefined;
    /** Available quantity at or below which the part should be reordered at this location. */
    reorderThreshold?: number | undefined;
    /** Quantity reserved against work orders at this location. */
    reservedQuantity?: number | undefined;
    /** Row within the location where the part is stored. */
    row?: string | undefined;
    unitCost?: Samsara.EntityCreateStockMovementMoneyTypeResponseBody | undefined;
    /** Unit of measure that the quantity fields on this record are expressed in. */
    unitOfMeasureType?: string | undefined;
    /** Time when the inventory level record was last updated. */
    updatedAtTime?: string | undefined;
}
