// This file was auto-generated by Fern from our API Definition.

/**
 * Reference to a WorkOrder
 */
export interface EntityUpcomingPreventativeMaintenanceWorkOrderRefTypeResponseBody {
    /** The ID of the referenced WorkOrder. */
    id: string;
}
