// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * TimeEntry object
 */
export interface EntityListTimeEntriesTypeResponseBody {
    /** Non-repair activity associated with the time entry. Omitted for work-order time. */
    activityType?: string | undefined;
    /** Time when the technician clocked in. */
    clockInAtTime?: string | undefined;
    clockInLocation?: Samsara.ListTimeEntriesEntityTimeEntryTimeEntryLocationTypeResponseBody | undefined;
    /** Surface that recorded the clock-in. */
    clockInSource?: string | undefined;
    /** Time when the technician clocked out. Omitted while the entry is in progress. */
    clockOutAtTime?: string | undefined;
    clockOutLocation?: Samsara.ListTimeEntriesEntityTimeEntryTimeEntryLocationTypeResponseBody | undefined;
    /** Method that ended the time entry. */
    clockOutMethodType?: string | undefined;
    /** Surface that recorded the clock-out. */
    clockOutSource?: string | undefined;
    /** Time when the time entry was created. */
    createdAtTime?: string | undefined;
    /** Time when the time entry was deleted. Deleted records contain only the ID, this field, and deletedByUserId when available. */
    deletedAtTime?: string | undefined;
    /** Dashboard user ID that deleted the time entry, when available. */
    deletedByUserId?: string | undefined;
    hourlyRate?: Samsara.ListTimeEntriesEntityTimeEntryMoneyTypeResponseBody | undefined;
    /** Stable unique identifier for the time entry. */
    id?: string | undefined;
    /** Samsara Place currently linked to the work order's maintenance site captured at clock-in. */
    placeId?: string | undefined;
    /** Work-order service-task instance associated with the time entry, when present. */
    serviceTaskId?: string | undefined;
    /** Whether the time entry is in progress or completed. */
    timeEntryStatus?: string | undefined;
    /** Time when the time entry was last updated. The feed window and ordering operate on this field. */
    updatedAtTime?: string | undefined;
    /** Dashboard user ID of the technician. Omitted when the technician is not linked to a dashboard user. */
    userId?: string | undefined;
    /** Work order associated with the time entry. Omitted for non-repair activities. */
    workOrderId?: string | undefined;
}
