// This file was auto-generated by Fern from our API Definition.

/**
 * Equipment header fields.
 */
export interface EquipmentHeaderWithAdditionalFieldsResponseBody {
    /** The unique Samsara ID of the equipment. This is automatically generated when the Equipment object is created. It cannot be changed. */
    EquipmentID?: string | undefined;
    /** The model of the equipment. */
    Model?: string | undefined;
    /** The make of the equipment. */
    OEMName?: string | undefined;
    /** The PIN number of the equipment. */
    PIN?: string | undefined;
    /** The serial number of the equipment. */
    SerialNumber?: string | undefined;
    /** Telematics unit install date in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00). */
    UnitInstallDateTime?: string | undefined;
}
