/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Engine RPM reading.
 */
export interface EquipmentEngineRpm {
    time: Samsara.EquipmentTime;
    /** The revolutions per minute of the engine. */
    value: number;
}
