// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Contains filters that are going to be applied to this report run.
 */
export interface FiltersRequestBody {
    primaryTimeRange?: Samsara.PrimaryTimeRangeRequestBody | undefined;
}
