// This file was auto-generated by Fern from our API Definition.

/**
 * A labelled quantity for an order task.
 */
export interface FleetOrderQuantityInputRequestBody {
    /** Optional capacity UUID for the task hub. */
    capacityId?: string | undefined;
    /** Human-readable quantity label. */
    label: string;
    /** Finite, non-negative quantity value. */
    value: number;
}
