// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * An action belonging to a canonical order.
 */
export interface FleetOrderTaskObjectResponseBody {
    /** Creation timestamp in RFC 3339 format. */
    createdAtTime: string;
    /** Task-specific customer metadata. */
    customerProperties: Samsara.FleetOrderCustomerPropertyObjectResponseBody[];
    /** Dispatcher-visible note. */
    dispatcherNotes?: string | undefined;
    /** Driver-visible note. */
    driverNotes?: string | undefined;
    /** Hub UUID for the task. */
    hubId: string;
    /** Opaque task ID. */
    id: string;
    /** Task position constraint.  Valid values: `unknown`, `none`, `first`, `last` */
    positionConstraintType: FleetOrderTaskObjectResponseBody.PositionConstraintType;
    /** Task quantities. */
    quantities: Samsara.FleetOrderQuantityObjectResponseBody[];
    /** Route ID when this task is attached to a route. */
    routeId?: string | undefined;
    /** Expected service duration in seconds. */
    serviceDurationSeconds?: number | undefined;
    serviceLocation?: Samsara.FleetOrderServiceLocationObjectResponseBody | undefined;
    /** Task service windows. */
    serviceWindows: Samsara.FleetOrderServiceWindowObjectResponseBody[];
    /** Task type.  Valid values: `unknown`, `delivery`, `pickup`, `pickupDelivery` */
    taskType: FleetOrderTaskObjectResponseBody.TaskType;
    /** Last update timestamp in RFC 3339 format. */
    updatedAtTime: string;
}

export namespace FleetOrderTaskObjectResponseBody {
    /** Task position constraint.  Valid values: `unknown`, `none`, `first`, `last` */
    export const PositionConstraintType = {
        Unknown: "unknown",
        None: "none",
        First: "first",
        Last: "last",
    } as const;
    export type PositionConstraintType = (typeof PositionConstraintType)[keyof typeof PositionConstraintType];
    /** Task type.  Valid values: `unknown`, `delivery`, `pickup`, `pickupDelivery` */
    export const TaskType = {
        Unknown: "unknown",
        Delivery: "delivery",
        Pickup: "pickup",
        PickupDelivery: "pickupDelivery",
    } as const;
    export type TaskType = (typeof TaskType)[keyof typeof TaskType];
}
