// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface FleetInstallerPhotoUploadsGetFleetInstallerPhotoUploadsResponseBody {
    /** Upload sessions ordered by updatedAtTime ascending. Up to 25 results per page. */
    data: Samsara.FleetInstallerPhotoUploadSessionResponseBody[];
    pagination: Samsara.GoaPaginationResponseResponseBody;
}
