// This file was auto-generated by Fern from our API Definition.

/**
 * Defines a column in a table form input field.
 */
export interface FormsTableColumnObjectResponseBody {
    /** Unique identifier for the column. */
    id: string;
    /** Label of the column. */
    label: string;
    /** Type of the column field.  Valid values: `text`, `number`, `datetime`, `check_boxes`, `multiple_choice`, `signature`, `media`, `person`, `barcode` */
    type: FormsTableColumnObjectResponseBody.Type;
}

export namespace FormsTableColumnObjectResponseBody {
    /** Type of the column field.  Valid values: `text`, `number`, `datetime`, `check_boxes`, `multiple_choice`, `signature`, `media`, `person`, `barcode` */
    export const Type = {
        Text: "text",
        Number: "number",
        Datetime: "datetime",
        CheckBoxes: "check_boxes",
        MultipleChoice: "multiple_choice",
        Signature: "signature",
        Media: "media",
        Person: "person",
        Barcode: "barcode",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
