/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * The value of a person form input field.
 */
export interface FormsPersonValueObjectResponseBody {
    person: SamsaraApi.FormsPersonObjectResponseBody;
}
