// This file was auto-generated by Fern from our API Definition.

/**
 * A single barcode entry in a form submission request.
 */
export interface FormSubmissionRequestBarcodeObjectRequestBody {
    /** The captured barcode value. */
    value: string;
}
