// This file was auto-generated by Fern from our API Definition.

/**
 * The value of a check boxes form input field. Only valid for check boxes form input fields.
 */
export interface FormSubmissionRequestCheckBoxesValueObjectRequestBody {
    valueIds: string[];
}
