// This file was auto-generated by Fern from our API Definition.

/**
 * The details of a form approval. Only valid for forms that require approvals.
 */
export interface FormSubmissionRequestApprovalDetailsRequestBody {
    /** Comment for the approval decision. Sometimes required when updating status to 'changesRequested'. Only valid when requesting changes or approving a form submission. */
    comment?: string;
}
