// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Forms input field request body object.
 */
export interface FormSubmissionRequestFieldInputObjectRequestBody {
    assetValue?: Samsara.FormSubmissionRequestAssetValueObjectRequestBody;
    checkBoxesValue?: Samsara.FormSubmissionRequestCheckBoxesValueObjectRequestBody;
    dateTimeValue?: Samsara.FormSubmissionRequestDateTimeValueObjectRequestBody;
    geofenceValue?: Samsara.FormSubmissionRequestGeofenceValueObjectRequestBody;
    /** ID of the forms input field object. */
    id: string;
    multipleChoiceValue?: Samsara.FormSubmissionRequestMultipleChoiceValueObjectRequestBody;
    numberValue?: Samsara.FormSubmissionRequestNumberValueObjectRequestBody;
    personValue?: Samsara.FormSubmissionRequestPersonValueObjectRequestBody;
    tableValue?: Samsara.FormSubmissionRequestTableValueObjectRequestBody;
    textValue?: Samsara.FormSubmissionRequestTextValueObjectRequestBody;
    /** Type of the field.  Valid values: `number`, `text`, `multiple_choice`, `check_boxes`, `datetime`, `asset`, `person`, `table`, `geofence` */
    type: FormSubmissionRequestFieldInputObjectRequestBody.Type;
}

export namespace FormSubmissionRequestFieldInputObjectRequestBody {
    /** Type of the field.  Valid values: `number`, `text`, `multiple_choice`, `check_boxes`, `datetime`, `asset`, `person`, `table`, `geofence` */
    export const Type = {
        Number: "number",
        Text: "text",
        MultipleChoice: "multiple_choice",
        CheckBoxes: "check_boxes",
        Datetime: "datetime",
        Asset: "asset",
        Person: "person",
        Table: "table",
        Geofence: "geofence",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
