/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Form Template section object.
 */
export interface FormTemplateSectionObjectResponseBody {
    /** The index of the first field from the fields array that is in this section. Index 0 represents the first field definition of the fields array. */
    fieldIndexFirstInclusive: number;
    /** The index of the last field from the fields array that is in this section. */
    fieldIndexLastInclusive: number;
    /** Identifier of the section. */
    id: string;
    /** Label of the section. */
    label: string;
}
