/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

export interface FormSubmissionsGetFormSubmissionsStreamResponseBody {
    /** List of form submissions. */
    data: SamsaraApi.FormSubmissionResponseObjectResponseBody[];
    pagination: SamsaraApi.GoaPaginationResponseResponseBody;
}
