/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * The value of a geofence form input field.
 */
export interface FormsGeofenceValueObjectResponseBody {
    geofence: Samsara.FormsGeofenceObjectResponseBody;
}
