/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * The value of an asset form input field. Only valid for asset form input fields.
 */
export interface FormSubmissionRequestAssetValueObjectRequestBody {
    asset: Samsara.FormSubmissionRequestAssetObjectRequestBody;
}
