/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * Dictionary containing summarized vehicle report data.
 */
export interface FuelEnergyVehicleReportDataObjectResponseBody {
    /** List of summarized vehicle reports. */
    vehicleReports: SamsaraApi.FuelEnergyVehicleReportObjectResponseBody[];
}
