/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Closest geofence based on 1000 meter radial search.
 */
export interface GeofenceResponseResponseBody {
    /** A map of external ids */
    externalIds?: Record<string, string>;
    /** Unique ID of the geofence object. */
    id?: string;
}
