// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface GetReportRunsDataObjectResponseBody {
    /** Columns of this report run. */
    columns: Samsara.ReportColumnsObjectResponseBody[];
    /** Array where each inner array represents a row of data, and each element in the inner array is a value for the column. Inner array items are nullable, data types: float64, string, timestamp as string in RFC3339 format. The number of columns defined in the report run is to the number of inner array items. */
    rows: Record<string, unknown>[][];
    /** Status of the report run.  Valid values: `complete`, `pending`, `failed`, `canceled`, `unknown` */
    status: GetReportRunsDataObjectResponseBody.Status;
}

export namespace GetReportRunsDataObjectResponseBody {
    /** Status of the report run.  Valid values: `complete`, `pending`, `failed`, `canceled`, `unknown` */
    export const Status = {
        Complete: "complete",
        Pending: "pending",
        Failed: "failed",
        Canceled: "canceled",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
