// This file was auto-generated by Fern from our API Definition.

/**
 * A minified document type object
 */
export interface GoaDocumentTypeTinyResponseResponseBody {
    /** ID of the document type. */
    id?: string;
    /** Name of the document type. */
    name?: string;
}
