/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

export interface HosDailyLogsGetHosDailyLogsResponseBody {
    /** List of drivers and their HOS daily logs data. */
    data: SamsaraApi.HosDailyLogsObjectResponseBody[];
    pagination: SamsaraApi.GoaPaginationResponseResponseBody;
}
