// This file was auto-generated by Fern from our API Definition.

/**
 * Details specific to HOS Violation
 */
export interface HosViolationTriggerDetailsObjectResponseBody {
    /** Alert if driver has this specified time until driving causes an HOS violation. */
    maxUntilViolationMilliseconds: number;
    /** The type of HOS violation.  Valid values: `CaliforniaMealbreakMissed`, `CycleHoursOn`, `DailyDrivingHours`, `DailyOnDutyHours`, `Invalid`, `RestbreakMissed`, `ShiftDrivingHours`, `ShiftHours`, `ShiftOnDutyHours`, `UnsubmittedLogs` */
    violation: HosViolationTriggerDetailsObjectResponseBody.Violation;
}

export namespace HosViolationTriggerDetailsObjectResponseBody {
    /** The type of HOS violation.  Valid values: `CaliforniaMealbreakMissed`, `CycleHoursOn`, `DailyDrivingHours`, `DailyOnDutyHours`, `Invalid`, `RestbreakMissed`, `ShiftDrivingHours`, `ShiftHours`, `ShiftOnDutyHours`, `UnsubmittedLogs` */
    export const Violation = {
        CaliforniaMealbreakMissed: "CaliforniaMealbreakMissed",
        CycleHoursOn: "CycleHoursOn",
        DailyDrivingHours: "DailyDrivingHours",
        DailyOnDutyHours: "DailyOnDutyHours",
        Invalid: "Invalid",
        RestbreakMissed: "RestbreakMissed",
        ShiftDrivingHours: "ShiftDrivingHours",
        ShiftHours: "ShiftHours",
        ShiftOnDutyHours: "ShiftOnDutyHours",
        UnsubmittedLogs: "UnsubmittedLogs",
    } as const;
    export type Violation = (typeof Violation)[keyof typeof Violation];
}
