// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Updated hub location object
 */
export interface HubLocationUpdatedObjectResponseBody {
    /** The physical address of the location */
    address: string;
    /** The timestamp (in UTC) when the location was created */
    createdAt: string;
    /** The customer-provided identifier for the location */
    customerLocationId: string;
    /** Instructions for the driver */
    driverInstructions: string;
    /** The ID of the hub this location belongs to */
    hubId: string;
    /** The Samsara-generated unique identifier (UUID) for the location */
    id: string;
    /** Indicates if the location is a depot */
    isDepot: boolean;
    /** Latitude coordinate of the location */
    latitude: number;
    /** Longitude coordinate of the location */
    longitude: number;
    /** The name of the location */
    name: string;
    /** Notes for the planner */
    plannerNotes: string;
    /** Estimated service time at this location in seconds */
    serviceTimeSeconds: number;
    /** An array of time windows during which service can be performed at this location */
    serviceWindows: Samsara.ServiceWindowObjectResponseBody[];
    /** An array of skills required for service at this location */
    skillsRequired: Samsara.SkillObjectResponseBody[];
    /** The timestamp (in UTC) when the location was last updated */
    updatedAt: string;
}
