// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface HubLocationsCreateHubLocationsResponseBody {
    /** Created hub locations data */
    data: Samsara.HubLocationCreatedObjectResponseBody[];
}
