// This file was auto-generated by Fern from our API Definition.

/**
 * A reference to a resource.
 */
export interface IdReferenceObjectRequestBody {
    /** The unique identifier of the resource. */
    id: string;
}
