// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 *  A job representing the async generation of IFTA mileage segments. The job should be polled until the state is terminal.
 */
export interface IftaDetailJobResponseBody {
    args: Samsara.IftaDetailJobArgsResponseBody;
    /**  The time this job completed successfully. */
    completedAtTime?: string;
    /** A message containing additional details about the job, if available. */
    details?: string;
    /**  The time this job failed. */
    failedAtTime?: string;
    /** A list of files generated by this job. This field will be omitted when the job status is "Failed" or no data exists with the provided job arguments. Read about the file structure [here](/docs/ifta-detail-csv). */
    files?: Samsara.IftaDetailJobOutputResponseBody[];
    /**  The ID used to retrieve this job. */
    jobId: string;
    /**  The status of this job. `jobStatus` can be one of Requested, Processing, Completed, or Failed.  Valid values: `Requested`, `Processing`, `Completed`, `Failed` */
    jobStatus: IftaDetailJobResponseBody.JobStatus;
    /**  The time this job was requested for creation. */
    requestedAtTime: string;
    /**  The time this job started processing. */
    startedAtTime?: string;
}

export namespace IftaDetailJobResponseBody {
    /**  The status of this job. `jobStatus` can be one of Requested, Processing, Completed, or Failed.  Valid values: `Requested`, `Processing`, `Completed`, `Failed` */
    export const JobStatus = {
        Requested: "Requested",
        Processing: "Processing",
        Completed: "Completed",
        Failed: "Failed",
    } as const;
    export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];
}
