// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Dictionary containing summarized vehicle report data.
 */
export interface IftaVehicleReportDataObjectResponseBody {
    /** The specified month duration for this IFTA report. */
    month?: string | undefined;
    /** The specified quarter duration for this IFTA report. */
    quarter?: string | undefined;
    troubleshooting?: Samsara.IftaReportTroubleshootingObjectResponseBody | undefined;
    /** List of summarized vehicle reports. */
    vehicleReports: Samsara.IftaVehicleReportObjectResponseBody[];
    /** The specified year for this IFTA report. */
    year: number;
}
