// This file was auto-generated by Fern from our API Definition.

/**
 * Enables AI detection of inattentive driving events.
 */
export interface InattentiveDrivingDetectionAlertSettingsObjectResponseBody {
    /** Indicates whether in-cab audio alerts for inattentive driving are turned on. */
    hasInCabAudioAlertsEnabled?: boolean | undefined;
    /** Indicates whether AI event detection for inattentive driving is turned on. */
    isEnabled?: boolean | undefined;
    /** Severity of inattentive driving events. Options include low (alerts for all events), medium (alerts for medium and high severity events), and high (alerts for high severity events only).  Valid values: `low`, `medium`, `high` */
    severity?: InattentiveDrivingDetectionAlertSettingsObjectResponseBody.Severity | undefined;
    /** Alert when speed is over this many miles per hour. */
    speedingThresholdMph?: number | undefined;
}

export namespace InattentiveDrivingDetectionAlertSettingsObjectResponseBody {
    /** Severity of inattentive driving events. Options include low (alerts for all events), medium (alerts for medium and high severity events), and high (alerts for high severity events only).  Valid values: `low`, `medium`, `high` */
    export const Severity = {
        Low: "low",
        Medium: "medium",
        High: "high",
    } as const;
    export type Severity = (typeof Severity)[keyof typeof Severity];
}
