// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Details specific to Inside Geofence
 */
export interface InsideGeofenceTriggerDetailsObjectResponseBody {
    location: Samsara.LocationObjectResponseBody;
    /** The number of milliseconds the trigger needs to stay active before alerting. */
    minDurationMilliseconds: number;
}
