// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Job object to be passed back
 */
export interface JobResponseObjectResponseBody {
    address: Samsara.JobLocationResponseObjectResponseBody;
    /** When the job was created */
    createdAt: string;
    /** Customer name for job */
    customerName: string;
    /** End date of job in RFC 3339 format */
    endDate: string;
    /** fleet devices in this job (cannot have both industrial assets and fleet devices in the same job) */
    fleetDevices?: Samsara.FleetDeviceObjectResponseBody[];
    /** Job id */
    id: string;
    /** Industrial Assets in this job (cannot have both industrial assets and fleet devices in the same job) */
    industrialAssets?: Samsara.IndustrialAssetObjectResponseBody[];
    /** When the job was last modified */
    modifiedAt: string;
    /** Job name */
    name: string;
    /** Notes for the upcoming job */
    notes: string;
    /** Specifies the time window (in milliseconds) after a stop's scheduled arrival time during which the stop is considered 'on-time'. */
    ontimeWindowAfterArrivalMs?: number;
    /** Specifies the time window (in milliseconds) before a stop's scheduled arrival time during which the stop is considered 'on-time'. */
    ontimeWindowBeforeArrivalMs?: number;
    /** Start date of job in RFC 3339 format */
    startDate: string;
    /** The current job status  Valid values: `active`, `scheduled`, `completed` */
    status: JobResponseObjectResponseBody.Status;
    /** Samsara uuid */
    uuid: string;
}

export namespace JobResponseObjectResponseBody {
    /** The current job status  Valid values: `active`, `scheduled`, `completed` */
    export const Status = {
        Active: "active",
        Scheduled: "scheduled",
        Completed: "completed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
