// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface JobsPatchJobResponseBody {
    data: Samsara.JobResponseObjectResponseBody;
    /** The job id of the failed request */
    id?: string | undefined;
    /** The uuid of the failed request */
    uuid?: string | undefined;
}
