/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * A list of tags.
 */
export interface ListTagsResponse {
    data?: SamsaraApi.Tag[];
    pagination?: SamsaraApi.PaginationResponse;
}
