// This file was auto-generated by Fern from our API Definition.

/**
 * WarrantyClaimStatusHistory object
 */
export interface ListWarrantyClaimsEntityWarrantyClaimWarrantyClaimStatusHistoryTypeResponseBody {
    /** When the transition occurred. */
    happenedAtTime?: string | undefined;
    /** The status the claim moved into.  Valid values: `unknown`, `created`, `submitted`, `inReview`, `approved`, `rejected`, `resubmitted`, `reimbursed` */
    status?: ListWarrantyClaimsEntityWarrantyClaimWarrantyClaimStatusHistoryTypeResponseBody.Status | undefined;
    /** ID of the user who made the change. */
    userId?: string | undefined;
}

export namespace ListWarrantyClaimsEntityWarrantyClaimWarrantyClaimStatusHistoryTypeResponseBody {
    /** The status the claim moved into.  Valid values: `unknown`, `created`, `submitted`, `inReview`, `approved`, `rejected`, `resubmitted`, `reimbursed` */
    export const Status = {
        Unknown: "unknown",
        Created: "created",
        Submitted: "submitted",
        InReview: "inReview",
        Approved: "approved",
        Rejected: "rejected",
        Resubmitted: "resubmitted",
        Reimbursed: "reimbursed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
