// This file was auto-generated by Fern from our API Definition.

/**
 * Pagination information
 */
export interface ListHubLocationsResponsePaginationResponseBody {
    /** Cursor for the last item in the page */
    endCursor?: string | undefined;
    /** Whether there are more pages available */
    hasNextPage: boolean;
}
