// This file was auto-generated by Fern from our API Definition.

export interface MultipleChoiceValueObjectResponseBody {
    /** Boolean representing if the choice has been selected. */
    selected?: boolean;
    /** Description of the choice. */
    value?: string;
}
