// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * A single numeric data point of a data input.
 */
export interface NumberDataPoint {
    time?: Samsara.Time;
    /** Numeric value of the data point. */
    value?: number;
}
