/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * Information about your organization.
 */
export interface OrganizationInfoObject {
    carrierSettings?: SamsaraApi.OrganizationInfoCarrierSettings;
    /** ID of the organization. */
    id?: string;
    /** Name of organization. */
    name?: string;
}
