/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Details specific to Out Of Route.
 */
export interface OutOfRouteResponseBody {
    driver?: Samsara.AlertObjectDriverResponseBody;
    trailer?: Samsara.AlertObjectTrailerResponseBody;
    vehicle?: Samsara.AlertObjectVehicleResponseBody;
}
