// This file was auto-generated by Fern from our API Definition.

/**
 * Identifying information for a device involved in a pairing operation.
 */
export interface PairResultDeviceObjectResponseBody {
    /** The unique Samsara ID of the device. */
    id: string;
    /** The name of the device. */
    name?: string | undefined;
    /** The serial number of the device. */
    serial: string;
    /** The type of the device.  Valid values: `vehicle`, `asset`, `equipment`, `trailer`, `industrial`, `assetTag` */
    type: PairResultDeviceObjectResponseBody.Type;
}

export namespace PairResultDeviceObjectResponseBody {
    /** The type of the device.  Valid values: `vehicle`, `asset`, `equipment`, `trailer`, `industrial`, `assetTag` */
    export const Type = {
        Vehicle: "vehicle",
        Asset: "asset",
        Equipment: "equipment",
        Trailer: "trailer",
        Industrial: "industrial",
        AssetTag: "assetTag",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
