// This file was auto-generated by Fern from our API Definition.

/**
 * A response that corresponds to an element in the original request body.
 */
export interface PatchAssetDataOutputsSingleResponseResponseBody {
    /** If the request failed, this displays the error message. */
    errorMessage?: string;
    /** The data output ID. */
    id: string;
    /** The status code of the request. 200 indicates the request succeeded for this data output. 500 indicates an internal server error. */
    statusCode: number;
}
