/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * What the duty status durations on the driver’s log would be if all pending carrier edits are accepted by the driver.
 */
export interface PendingDutyStatusDurationsObjectResponseBody {
    /** Duration the driver was active for in the log period in milliseconds. */
    activeDurationMs?: number;
    /** Duration the driver was driving for in the log period in milliseconds. */
    driveDurationMs?: number;
    /** Duration the driver was off duty for in the log period in milliseconds. */
    offDutyDurationMs?: number;
    /** Duration the driver was on duty for in the log period in milliseconds. */
    onDutyDurationMs?: number;
    /** Duration the driver was driving for personal conveyance for in the log period in milliseconds. */
    personalConveyanceDurationMs?: number;
    /** Duration the driver was in their sleeper berth for in the log period in milliseconds. */
    sleeperBerthDurationMs?: number;
    /** Duration the driver was waiting for in the log period in milliseconds. */
    waitingTimeDurationMs?: number;
    /** Duration the driver was driving for yard moves for in the log period in milliseconds. */
    yardMoveDurationMs?: number;
}
