// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Details specific to Person Detected.
 */
export interface PersonDetectedResponseBody {
    cameraStream?: Samsara.AlertObjectOnvifCameraStreamResponseBody;
}
