// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Order service time configuration for a hub location row.
 */
export interface PlaceHubLocationOrderServiceTimeInputRequestBody {
    /** Capacity-based service times for variable mode. */
    capacityServiceTimes?: Samsara.PlaceHubLocationCapacityServiceTimeInputRequestBody[] | undefined;
    /** Fixed order service time in seconds when applicable. */
    fixedTimeSeconds?: number | undefined;
    /** Mode: fixed or variable.  Valid values: `fixed`, `variable`, `unknown`, `unspecified` */
    modeType: PlaceHubLocationOrderServiceTimeInputRequestBody.ModeType;
}

export namespace PlaceHubLocationOrderServiceTimeInputRequestBody {
    /** Mode: fixed or variable.  Valid values: `fixed`, `variable`, `unknown`, `unspecified` */
    export const ModeType = {
        Fixed: "fixed",
        Variable: "variable",
        Unknown: "unknown",
        Unspecified: "unspecified",
    } as const;
    export type ModeType = (typeof ModeType)[keyof typeof ModeType];
}
