// This file was auto-generated by Fern from our API Definition.

/**
 * Navigation location.
 */
export interface PlaceNavigationLocationResponseResponseBody {
    /** Driver instructions. */
    driverInstructions?: string | undefined;
    /** Latitude. */
    latitude: number;
    /** Navigation location type. */
    locationType: string;
    /** Longitude. */
    longitude: number;
    /** Location name. */
    name: string;
}
