// This file was auto-generated by Fern from our API Definition.

/**
 * Named business contact for a place.
 */
export interface PostPlaceBusinessContactInputRequestBody {
    /** Contact email. Opaque string; max 100 characters. */
    email?: string | undefined;
    /** Display name. Max 50 characters. */
    name?: string | undefined;
    /** Contact phone. Opaque string; max 15 characters. */
    phoneNumber?: string | undefined;
}
