/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response after successfully adding a Fuel Purchase transaction
 */
export interface PostFuelPurchaseResponseBodyResponseBody {
    /** Universally unique identifier for the fuel purchase. */
    uuid: string;
}
