// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * A customer-set price for a specific fuel type at this station.
 */
export interface PreferredStationPriceInputRequestBody {
    /** The fuel type this price applies to.  Valid values: `gasoline`, `diesel`, `biodiesel`, `flexibleFuelE85`, `ethanolE100`, `renewableDiesel`, `m100`, `cng`, `lng`, `lpg`, `rng`, `fcev`, `unknown` */
    fuelType: PreferredStationPriceInputRequestBody.FuelType;
    grossPrice?: Samsara.PreferredStationGrossPriceRequestBody | undefined;
    netPrice?: Samsara.PreferredStationNetPriceRequestBody | undefined;
    /** Volume/energy unit.  Valid values: `liter`, `gallon`, `imperialGallon` */
    volumeUnit: PreferredStationPriceInputRequestBody.VolumeUnit;
}

export namespace PreferredStationPriceInputRequestBody {
    /** The fuel type this price applies to.  Valid values: `gasoline`, `diesel`, `biodiesel`, `flexibleFuelE85`, `ethanolE100`, `renewableDiesel`, `m100`, `cng`, `lng`, `lpg`, `rng`, `fcev`, `unknown` */
    export const FuelType = {
        Gasoline: "gasoline",
        Diesel: "diesel",
        Biodiesel: "biodiesel",
        FlexibleFuelE85: "flexibleFuelE85",
        EthanolE100: "ethanolE100",
        RenewableDiesel: "renewableDiesel",
        M100: "m100",
        Cng: "cng",
        Lng: "lng",
        Lpg: "lpg",
        Rng: "rng",
        Fcev: "fcev",
        Unknown: "unknown",
    } as const;
    export type FuelType = (typeof FuelType)[keyof typeof FuelType];
    /** Volume/energy unit.  Valid values: `liter`, `gallon`, `imperialGallon` */
    export const VolumeUnit = {
        Liter: "liter",
        Gallon: "gallon",
        ImperialGallon: "imperialGallon",
    } as const;
    export type VolumeUnit = (typeof VolumeUnit)[keyof typeof VolumeUnit];
}
