// This file was auto-generated by Fern from our API Definition.

/**
 * Primary time range of the report that not all datasets and report configs support.
 */
export interface PrimaryTimeRangeResponseBody {
    /** End time of the time range filter in RFC3339 format. */
    endTime: string;
    /** Start time of the time range filter in RFC3339 format. */
    startTime: string;
}
