// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Qualification input field request body object.
 */
export interface QualificationRecordRequestFieldInputObjectRequestBody {
    checkBoxesValue?: Samsara.FormSubmissionRequestCheckBoxesValueObjectRequestBody | undefined;
    dateTimeValue?: Samsara.FormSubmissionRequestDateTimeValueObjectRequestBody | undefined;
    /** ID of the qualification input field object. */
    id: string;
    mediaValue?: Samsara.FormSubmissionRequestMediaValueObjectRequestBody | undefined;
    multipleChoiceValue?: Samsara.FormSubmissionRequestMultipleChoiceValueObjectRequestBody | undefined;
    numberValue?: Samsara.FormSubmissionRequestNumberValueObjectRequestBody | undefined;
    signatureValue?: Samsara.FormSubmissionRequestSignatureValueObjectRequestBody | undefined;
    tableValue?: Samsara.FormSubmissionRequestTableValueObjectRequestBody | undefined;
    textValue?: Samsara.FormSubmissionRequestTextValueObjectRequestBody | undefined;
    /** Type of the qualification field.  Valid values: `number`, `text`, `multiple_choice`, `check_boxes`, `datetime`, `table`, `media`, `signature` */
    type: QualificationRecordRequestFieldInputObjectRequestBody.Type;
}

export namespace QualificationRecordRequestFieldInputObjectRequestBody {
    /** Type of the qualification field.  Valid values: `number`, `text`, `multiple_choice`, `check_boxes`, `datetime`, `table`, `media`, `signature` */
    export const Type = {
        Number: "number",
        Text: "text",
        MultipleChoice: "multiple_choice",
        CheckBoxes: "check_boxes",
        Datetime: "datetime",
        Table: "table",
        Media: "media",
        Signature: "signature",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
