// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Details specific to Reefer Temperature.
 */
export interface ReeferTemperatureResponseBody {
    driver?: Samsara.AlertObjectDriverResponseBody | undefined;
    trailer?: Samsara.AlertObjectTrailerResponseBody | undefined;
    vehicle?: Samsara.AlertObjectVehicleResponseBody | undefined;
}
