// This file was auto-generated by Fern from our API Definition.

/**
 * Special handling flags for the passenger. Omitted flags default to false.
 */
export interface RidershipPassengerSpecialInstructionsInputRequestBody {
    /** Whether a guardian is required for the passenger. */
    isGuardianRequired?: boolean | undefined;
    /** Whether the passenger requires special education accommodations. */
    isSpecialEducation?: boolean | undefined;
}
