// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * A canonical order to upsert and attach to the containing route stop.
 */
export interface RouteStopOrderUpsertInputRequestBody {
    /** Order-specific customer metadata. */
    customerProperties?: Samsara.FleetOrderCustomerPropertyObjectRequestBody[] | undefined;
    /** Org-scoped external identifiers. */
    externalIds?: RouteStopOrderUpsertInputRequestBody.ExternalIds | undefined;
    /** Existing Samsara order UUID. Required unless externalIds is supplied. */
    id?: string | undefined;
    /** Human-readable order label. */
    samsaraCustomerOrderName?: string | undefined;
    /** Tasks to upsert and attach to the containing stop. */
    tasks: Samsara.FleetOrderTaskUpsertInputRequestBody[];
}

export namespace RouteStopOrderUpsertInputRequestBody {
    /**
     * Org-scoped external identifiers.
     */
    export type ExternalIds = {};
}
