// This file was auto-generated by Fern from our API Definition.

/**
 * A minified driver object.
 */
export interface SafetyEventDriverObjectResponseBody {
    /** ID of the driver. */
    id?: string;
}
