// This file was auto-generated by Fern from our API Definition.

/**
 * The configurable safety infraction weights.
 */
export interface SafetyScoreConfigurationSettingsObjectResponseBody {
    /** Score weight for AI-detected inattentive driving behavior. */
    aiInattentiveDrivingDetectionWeight?: number;
    /** Score weight for crash behavior. */
    crashWeight?: number;
    /** Score weight for defensive driving behavior. This behavior has a positive impact on the safety score. */
    defensiveDrivingWeight?: number;
    /** Score weight for driver not yielding. */
    didNotYieldWeight?: number;
    /** Score weight for drowsy behavior. */
    drowsyWeight?: number;
    /** Score weight for eating/drinking behavior. */
    eatingDrinkingWeight?: number;
    /** Score weight for moderate (2-4s) following distance behavior. */
    followingDistanceModerateWeight?: number;
    /** Score weight for severe (0-2s) following distance behavior. */
    followingDistanceSevereWeight?: number;
    /** Score weight for following distance behavior. */
    followingDistanceWeight?: number;
    /** Score weight for forward collision warning behavior. */
    forwardCollisionWarningWeight?: number;
    /** Score weight for harsh acceleration behavior. */
    harshAccelWeight?: number;
    /** Score weight for harsh braking behavior. */
    harshBrakeWeight?: number;
    /** Score weight for harsh turn behavior. */
    harshTurnWeight?: number;
    /** Score weight for heavy speeding (20-30% over limit). */
    heavySpeedingWeight?: number;
    /** Score weight for inattentive driving behavior. */
    inattentiveDrivingWeight?: number;
    /** Score weight for lane departure behavior. */
    laneDepartureWeight?: number;
    /** Score weight for late response behavior. */
    lateResponseWeight?: number;
    /** Score weight for light speeding (0-10% over limit). */
    lightSpeedingWeight?: number;
    /** Score weight for max speed events. */
    maxSpeedWeight?: number;
    /** Score weight for mobile usage behavior. */
    mobileUsageWeight?: number;
    /** Score weight for moderate speeding (10-20% over limit). */
    moderateSpeedingWeight?: number;
    /** Score weight for near collision behavior. */
    nearCollisionWeight?: number;
    /** Score weight for no seatbelt behavior. */
    noSeatbeltWeight?: number;
    /** Score weight for obstructed camera behavior. */
    obstructedCameraWeight?: number;
    /** Score weight for driver running red light. */
    ranRedLightWeight?: number;
    /** Score weight for rolling stop behavior. */
    rollingStopWeight?: number;
    /** Score weight for severe speeding (over 30% over limit). */
    severeSpeedingWeight?: number;
    /** Score weight for smoking behavior. */
    smokingWeight?: number;
    /** Score weight for manual speeding event. */
    speedingWeight?: number;
    /** Score weight for vulnerable road user behavior. */
    vulnerableRoadUserWeight?: number;
}
