/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A sensor
 */
export interface SensorResponseBody {
    /** ID of the sensor */
    id: string;
    /** The MAC address of the sensor */
    mac: string;
    /** The name of the sensor */
    name: string;
}
