/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Work Order Service Task object.
 */
export interface ServiceTaskInstanceInputObjectRequestBody {
    /** ID of the service task instance. Only set if updating an existing service task instance. */
    id?: string;
    laborHourlyCost?: Samsara.WorkOrderMoneyObjectRequestBody;
    /** The time of labor needed */
    laborTimeMinutes?: number;
    partsCost?: Samsara.WorkOrderMoneyObjectRequestBody;
    /** ID of the service task. */
    serviceTaskId: string;
    /** The status of the service task.  Valid values: `Unknown`, `Open`, `In Progress`, `On Hold`, `Completed` */
    status: ServiceTaskInstanceInputObjectRequestBody.Status;
}

export namespace ServiceTaskInstanceInputObjectRequestBody {
    /**
     * The status of the service task.  Valid values: `Unknown`, `Open`, `In Progress`, `On Hold`, `Completed`
     */
    export type Status = "Unknown" | "Open" | "In Progress" | "On Hold" | "Completed";
    export const Status = {
        Unknown: "Unknown",
        Open: "Open",
        InProgress: "In Progress",
        OnHold: "On Hold",
        Completed: "Completed",
    } as const;
}
