// This file was auto-generated by Fern from our API Definition.

/**
 * A procedure subtask.
 */
export interface ServiceTaskProcedureSubtaskObjectResponseBody {
    /** Whether the procedure is complete. */
    isCompleted: boolean;
    /** The name of the procedure. */
    name: string;
}
