// This file was auto-generated by Fern from our API Definition.

/**
 * Service window
 */
export interface ServiceWindowObjectResponseBody {
    /** Days of the week when the service window applies */
    daysOfWeek: string[];
    /** End time of the service window */
    endTime: string;
    /** Start time of the service window */
    startTime: string;
}
