// This file was auto-generated by Fern from our API Definition.

/**
 * Information set here will be displayed in roadside inspections and in the transferred US DOT datafile.
 */
export interface SettingsComplianceResponseObjectResponseBody {
    /** [deprecated] Allow Unregulated Vehicles. This setting is deprecated as all organizations can now mark vehicles as unregulated. */
    allowUnregulatedVehiclesEnabled?: boolean | undefined;
    /** Enable Canada HOS */
    canadaHosEnabled?: boolean | undefined;
    /** Carrier name of the organization */
    carrierName?: string | undefined;
    /** DOT Number */
    dotNumber?: number | undefined;
    /** Enable Driver Auto-Duty */
    driverAutoDutyEnabled?: boolean | undefined;
    /** Drivers Can Edit Certified Log */
    editCertifiedLogsEnabled?: boolean | undefined;
    /** Force Manual Location For Duty Status Changes */
    forceManualLocationForDutyStatusChangesEnabled?: boolean | undefined;
    /** Force Review of Unassigned HOS */
    forceReviewUnassignedHosEnabled?: boolean | undefined;
    /** Office Address */
    mainOfficeFormattedAddress?: string | undefined;
    /** Persistent Duty Status */
    persistentDutyStatusEnabled?: boolean | undefined;
}
