// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * The start of a severe speeding event
 */
export interface SevereSpeedingStartedResponseObjectResponseBody {
    data: Samsara.SevereSpeedingStartedObjectResponseBody;
}
