/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * The start of a severe speeding event
 */
export interface SevereSpeedingStartedObjectResponseBody {
    /** The speeding start time in RFC 3339 format (Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00). */
    startTime: string;
    /** The trip start time in RFC 3339 format (Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00). */
    tripStartTime?: string;
    vehicle: SamsaraApi.VehicleResponseResponseBody;
}
