/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Details specific to Speed.
 */
export interface SpeedDataResponseBody {
    /** Current speed of the vehicle in kilometers per hour. */
    currentSpeedKilometersPerHour: number;
    driver?: Samsara.AlertObjectDriverResponseBody;
    /** Minimum duration of the current speed in milliseconds. */
    minDurationMilliseconds: number;
    /** Operation of the current and threshold comparison.  Valid values: `GREATER`, `INSIDE_RANGE`, `LESS`, `OUTSIDE_RANGE` */
    operation: SpeedDataResponseBody.Operation;
    /** Threshold speed of the vehicle in kilometers per hour. */
    thresholdSpeedKilometersPerHour: number;
    trailer?: Samsara.AlertObjectTrailerResponseBody;
    vehicle?: Samsara.AlertObjectVehicleResponseBody;
}

export namespace SpeedDataResponseBody {
    /**
     * Operation of the current and threshold comparison.  Valid values: `GREATER`, `INSIDE_RANGE`, `LESS`, `OUTSIDE_RANGE`
     */
    export type Operation = "GREATER" | "INSIDE_RANGE" | "LESS" | "OUTSIDE_RANGE";
    export const Operation = {
        Greater: "GREATER",
        InsideRange: "INSIDE_RANGE",
        Less: "LESS",
        OutsideRange: "OUTSIDE_RANGE",
    } as const;
}
