// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Enables custom speeding levels.
 */
export interface SpeedingSettingsObjectResponseBody {
    /** The speeding severity levels for an organization. */
    severityLevels?: Samsara.SpeedingSeverityLevelResponseBody[] | undefined;
    /** The unit of measurement for speeding  Valid values: `milesPerHour`, `kilometersPerHour`, `percentage` */
    unit?: SpeedingSettingsObjectResponseBody.Unit | undefined;
}

export namespace SpeedingSettingsObjectResponseBody {
    /** The unit of measurement for speeding  Valid values: `milesPerHour`, `kilometersPerHour`, `percentage` */
    export const Unit = {
        MilesPerHour: "milesPerHour",
        KilometersPerHour: "kilometersPerHour",
        Percentage: "percentage",
    } as const;
    export type Unit = (typeof Unit)[keyof typeof Unit];
}
