// This file was auto-generated by Fern from our API Definition.

/**
 * Details for stop task completed events.
 */
export interface StopTaskCompletedEventDetailsResponseBody {
    /** ID of the completed stop task. */
    taskId: string;
    /** Type of the completed stop task.  Valid values: `form`, `document` */
    taskType: StopTaskCompletedEventDetailsResponseBody.TaskType;
}

export namespace StopTaskCompletedEventDetailsResponseBody {
    /** Type of the completed stop task.  Valid values: `form`, `document` */
    export const TaskType = {
        Form: "form",
        Document: "document",
    } as const;
    export type TaskType = (typeof TaskType)[keyof typeof TaskType];
}
