/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * Details specific to Sudden Fuel Level Rise.
 */
export interface SuddenFuelLevelRiseResponseBody {
    /** The end time of the fuel level change in RFC 3339 format. */
    changeEndTime?: string;
    /** The start time of the fuel level change in RFC 3339 format. */
    changeStartTime?: string;
    driver?: SamsaraApi.AlertObjectDriverResponseBody;
    /** The fuel level after the sudden fuel level rise in millipercents. */
    fuelLevelAfterMillipercent?: number;
    /** The fuel level before the sudden fuel level rise in millipercents. */
    fuelLevelBeforeMillipercent?: number;
    location?: SamsaraApi.EventLocationResponseBody;
    vehicle?: SamsaraApi.AlertObjectVehicleResponseBody;
}
