/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

export interface TachographDriverFileListWrapper {
    driver?: Samsara.DriverTinyResponse;
    files?: Samsara.TachographDriverFileList;
}
