// This file was auto-generated by Fern from our API Definition.

/**
 * The door state of the reefer.
 */
export interface TrailerStatReeferDoorStateZone1TypeResponseBody {
    /** UTC timestamp in RFC 3339 format. */
    time: string;
    /** The door state of zone 2 of the reefer.  Valid values: `open`, `closed` */
    value: TrailerStatReeferDoorStateZone1TypeResponseBody.Value;
}

export namespace TrailerStatReeferDoorStateZone1TypeResponseBody {
    /** The door state of zone 2 of the reefer.  Valid values: `open`, `closed` */
    export const Value = {
        Open: "open",
        Closed: "closed",
    } as const;
    export type Value = (typeof Value)[keyof typeof Value];
}
