// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Door stats that have been emitted by the reefer.
 */
export interface TrailerStatReeferDoorStateZone3WithDecorationsTypeResponseBody {
    decorations?: Samsara.TrailerStatDecorationResponseBody | undefined;
    /** UTC timestamp in RFC 3339 format. */
    time: string;
    /** The door state of zone 2 of the reefer.  Valid values: `open`, `closed` */
    value: TrailerStatReeferDoorStateZone3WithDecorationsTypeResponseBody.Value;
}

export namespace TrailerStatReeferDoorStateZone3WithDecorationsTypeResponseBody {
    /** The door state of zone 2 of the reefer.  Valid values: `open`, `closed` */
    export const Value = {
        Open: "open",
        Closed: "closed",
    } as const;
    export type Value = (typeof Value)[keyof typeof Value];
}
