// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * GPS location data for the trailer.
 */
export interface TrailerStatGpsTypeResponseBody {
    /** Heading of the trailer in degrees. */
    headingDegrees?: number | undefined;
    /** GPS latitude represented in degrees. */
    latitude: number;
    /** GPS longitude represented in degrees. */
    longitude: number;
    reverseGeo?: Samsara.ReverseGeoObjectResponseBody | undefined;
    /** GPS speed of the trailer in miles per hour. */
    speedMilesPerHour?: number | undefined;
    /** UTC timestamp in RFC 3339 format. */
    time: string;
}
