// This file was auto-generated by Fern from our API Definition.

/**
 * Trailer GPS odometer event.
 */
export interface TrailerStatGpsOdometerMetersTypeResponseBody {
    /** UTC timestamp in RFC 3339 format. */
    time: string;
    /** Number of meters the trailer has traveled according to the GPS calculations and the manually specified odometer reading. */
    value: number;
}
