// This file was auto-generated by Fern from our API Definition.

/**
 * Label of the training course.
 */
export interface TrainingCourseLabelObjectResponseBody {
    /** Name of the course label. Valid values: “safety”. */
    name: string;
    /** Type of the course label. Valid values when course.label.name is ‘safety’: accel, braking, crashSharpTurn, rolloverProtection, yawControl, speeding, rolledStopSign, tileRollingRailroad, seatbeltPolicy, nearCollision, phonePolicy, drowsy, defensiveDriving, driverObstructionPolicy, didNotYield, distractedDriving, tailgating, laneDeparture, lateResponse, ranRedLight, forwardCollisionWarning, foodDrinkPolicy, smokingPolicy, maskPolicy, maxSpeed, severeSpeeding, drinkPolicy, foodPolicy, unknown. */
    type: string;
}
