/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

export interface TripsGetTripsResponseBody {
    /** List of trips */
    data: Samsara.TripResponseBody[];
    pagination: Samsara.GoaPaginationResponseResponseBody;
}
