// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Trip impacts on safety score.
 */
export interface TripsBreakdownResponseBody {
    /** Aggregated list of behaviors that occurred during the trip, one row for each unique type of behavior. */
    behaviors: Samsara.SafetyScoreBehaviorObjectResponseBody[];
    /** Distance driven during the trip. */
    driveDistanceMeters: number;
    /** ID of the driver associated with the trip. */
    driverId: string;
    /** Aggregated list of speeding events that occurred during the trip, one row for each unique type of speeding. */
    speeding: Samsara.SafetyScoreSpeedingObjectResponseBody[];
    /** [RFC 3339] Time the trip ended in UTC. */
    tripEndTime: string;
    /** Impact of the trip to the overall score. This is the effective sum of all risk factors in the trip. */
    tripScoreImpact: number;
    /** [RFC 3339] Time the trip started in UTC. */
    tripStartTime: string;
    /** ID of the vehicle associated with the trip. */
    vehicleId: string;
}
