/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

export interface TripsGetTripsResponseBody {
    /** List of trips */
    data: SamsaraApi.TripResponseBody[];
    pagination: SamsaraApi.GoaPaginationResponseResponseBody;
}
