// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * UpdatePurchaseOrderEntityPurchaseOrderTaxAdjustmentInput object
 */
export interface UpdatePurchaseOrderEntityPurchaseOrderTaxAdjustmentInputTypeRequestBody {
    /** Tax rate in basis points. Set exactly one of money or basisPoints. */
    basisPoints?: number | undefined;
    money?: Samsara.UpdatePurchaseOrderEntityPurchaseOrderMoneyInputTypeRequestBody | undefined;
}
