// This file was auto-generated by Fern from our API Definition.

/**
 * UpdatePartInventoryLocationEntityPartInventoryLocationMoneyInput object
 */
export interface UpdatePartInventoryLocationEntityPartInventoryLocationMoneyInputTypeRequestBody {
    /** Monetary amount as a decimal string in major currency units (e.g. "24.50"). */
    amount: string;
    /** ISO 4217 currency code, lowercased (e.g. "usd"). */
    currency: string;
}
