// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * UpdatePurchaseOrderEntityPurchaseOrderPurchaseOrderCoreChargeInput object
 */
export interface UpdatePurchaseOrderEntityPurchaseOrderPurchaseOrderCoreChargeInputTypeRequestBody {
    /** Whether the core charge is active or removed or disabled. */
    coreChargeStatus: string;
    /** ID of the returnable core part. */
    corePartSamsaraId?: string | undefined;
    recoverabilityPolicy?:
        | Samsara.UpdatePurchaseOrderEntityPurchaseOrderCoreRecoverabilityPolicyInputTypeRequestBody
        | undefined;
    /** ID of the vendor that receives returned cores. */
    returnRecipientVendorId?: string | undefined;
    unitCoreAmount?: Samsara.UpdatePurchaseOrderEntityPurchaseOrderMoneyInputTypeRequestBody | undefined;
}
