// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * UpdateWarrantyClaimEntityWarrantyClaimWarrantyClaimPart object
 */
export interface UpdateWarrantyClaimEntityWarrantyClaimWarrantyClaimPartTypeResponseBody {
    cost?: Samsara.UpdateWarrantyClaimEntityWarrantyClaimMoneyTypeResponseBody | undefined;
    /** Free-text part description. */
    description?: string | undefined;
    /** ID of the part definition being claimed. */
    partDefinitionId?: string | undefined;
    /** Specific part-instance ID. */
    partId?: string | undefined;
    /** Quantity claimed. */
    quantity?: number | undefined;
    /** Service task the part belongs to. */
    serviceTaskId?: string | undefined;
    /** Work order the part cost originated from. */
    sourceWorkOrderId?: string | undefined;
    /** Dotted VMRS code path (e.g. 034-005-001) associated with this part line. */
    vmrsCode?: string | undefined;
}
