// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * UpdateWarrantyClaimEntityWarrantyClaimWarrantyClaimLabor object
 */
export interface UpdateWarrantyClaimEntityWarrantyClaimWarrantyClaimLaborTypeResponseBody {
    cost?: Samsara.UpdateWarrantyClaimEntityWarrantyClaimMoneyTypeResponseBody | undefined;
    /** Free-text labor description. */
    description?: string | undefined;
    /** Service task the labor belongs to. */
    serviceTaskId?: string | undefined;
    /** Work order the labor cost originated from. */
    sourceWorkOrderId?: string | undefined;
    /** Dotted VMRS code path (e.g. 034-005-001) associated with this labor line. */
    vmrsCode?: string | undefined;
}
