// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface UploadedMediaObjectResponseBody {
    /** Timestamp, in RFC 3339 format, at which the media item was made available. Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00 */
    availableAtTime: string;
    /** Camera role for this media.  Valid values: `leftMirrorMount`, `leftSide`, `rightMirrorMount`, `rightSide`, `rearHigh`, `rearBumper`, `inCab`, `front`, `hopper`, `other1`, `other2`, `other3`, `other4`, `leftBev`, `rightBev`, `rearBev`, `frontBev`, `otherBev`, `bevNotUsed` */
    cameraRole?: UploadedMediaObjectResponseBody.CameraRole;
    /**  An end time in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00). */
    endTime: string;
    /** Input type for this media.  Valid values: `dashcamForwardFacing`, `dashcamInwardFacing`, `analog1`, `analog2`, `analog3`, `analog4` */
    input: UploadedMediaObjectResponseBody.Input;
    /** Type of media.  Valid values: `image`, `video` */
    mediaType: UploadedMediaObjectResponseBody.MediaType;
    /**  A start time in RFC 3339 format. Millisecond precision and timezones are supported. (Examples: 2019-06-13T19:08:25Z, 2019-06-13T19:08:25.455Z, OR 2015-09-15T14:00:12-04:00). */
    startTime: string;
    /** Trigger reason for this media capture.  Valid values: `api`, `panicButton`, `periodicStill`, `rfidEvent`, `safetyEvent`, `tripEndStill`, `tripStartStill`, `videoRetrieval` */
    triggerReason: UploadedMediaObjectResponseBody.TriggerReason;
    urlInfo?: Samsara.UrlInfoObjectResponseBody;
    /** Vehicle ID for which this media was captured. Examples: 1234 */
    vehicleId: string;
}

export namespace UploadedMediaObjectResponseBody {
    /** Camera role for this media.  Valid values: `leftMirrorMount`, `leftSide`, `rightMirrorMount`, `rightSide`, `rearHigh`, `rearBumper`, `inCab`, `front`, `hopper`, `other1`, `other2`, `other3`, `other4`, `leftBev`, `rightBev`, `rearBev`, `frontBev`, `otherBev`, `bevNotUsed` */
    export const CameraRole = {
        LeftMirrorMount: "leftMirrorMount",
        LeftSide: "leftSide",
        RightMirrorMount: "rightMirrorMount",
        RightSide: "rightSide",
        RearHigh: "rearHigh",
        RearBumper: "rearBumper",
        InCab: "inCab",
        Front: "front",
        Hopper: "hopper",
        Other1: "other1",
        Other2: "other2",
        Other3: "other3",
        Other4: "other4",
        LeftBev: "leftBev",
        RightBev: "rightBev",
        RearBev: "rearBev",
        FrontBev: "frontBev",
        OtherBev: "otherBev",
        BevNotUsed: "bevNotUsed",
    } as const;
    export type CameraRole = (typeof CameraRole)[keyof typeof CameraRole];
    /** Input type for this media.  Valid values: `dashcamForwardFacing`, `dashcamInwardFacing`, `analog1`, `analog2`, `analog3`, `analog4` */
    export const Input = {
        DashcamForwardFacing: "dashcamForwardFacing",
        DashcamInwardFacing: "dashcamInwardFacing",
        Analog1: "analog1",
        Analog2: "analog2",
        Analog3: "analog3",
        Analog4: "analog4",
    } as const;
    export type Input = (typeof Input)[keyof typeof Input];
    /** Type of media.  Valid values: `image`, `video` */
    export const MediaType = {
        Image: "image",
        Video: "video",
    } as const;
    export type MediaType = (typeof MediaType)[keyof typeof MediaType];
    /** Trigger reason for this media capture.  Valid values: `api`, `panicButton`, `periodicStill`, `rfidEvent`, `safetyEvent`, `tripEndStill`, `tripStartStill`, `videoRetrieval` */
    export const TriggerReason = {
        Api: "api",
        PanicButton: "panicButton",
        PeriodicStill: "periodicStill",
        RfidEvent: "rfidEvent",
        SafetyEvent: "safetyEvent",
        TripEndStill: "tripEndStill",
        TripStartStill: "tripStartStill",
        VideoRetrieval: "videoRetrieval",
    } as const;
    export type TriggerReason = (typeof TriggerReason)[keyof typeof TriggerReason];
}
