// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Basic information of an asset
 */
export interface V1Asset {
    /** Serial number of the host asset */
    assetSerialNumber?: string;
    cable?: Samsara.V1AssetCable;
    /** Engine hours */
    engineHours?: number;
    /** Asset ID */
    id: number;
    /** Asset name */
    name?: string;
    /** The ID of the Vehicle associated to the Asset (if present) */
    vehicleId?: number;
}
