// This file was auto-generated by Fern from our API Definition.

export interface V1AssetsReeferReeferStatsAmbientAirTemperature {
    /** Timestamp in Unix milliseconds since epoch. */
    changedAtMs?: number;
    /** Ambient temperature in millidegree Celsius. */
    tempInMilliC?: number;
}
