// This file was auto-generated by Fern from our API Definition.

export interface V1AssetReeferResponseReeferStatsReturnAirTemp {
    /** Timestamp in Unix milliseconds since epoch. */
    changedAtMs?: number;
    /** Return air temperature in millidegree Celsius. */
    tempInMilliC?: number;
}
