// This file was auto-generated by Fern from our API Definition.

export interface V1MachineHistoryResponseVibrations {
    X?: number | undefined;
    Y?: number | undefined;
    Z?: number | undefined;
    time?: number | undefined;
}
