// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

export interface V1MachineHistoryResponseMachines {
    /** Machine ID */
    id?: number | undefined;
    /** Machine name */
    name?: string | undefined;
    /** List of vibration datapoints, with timestamp and vibration measurement for x/y/z axis in mm/s */
    vibrations?: Samsara.V1MachineHistoryResponseVibrations[] | undefined;
}
