// This file was auto-generated by Fern from our API Definition.

/**
 * Contains information about a sensor.
 */
export interface V1Sensor {
    /** ID of the sensor. */
    id: number;
    /** MAC address of the sensor. */
    macAddress?: string;
    /** Name of the sensor. */
    name?: string;
}
