// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Safety score details for a vehicle
 */
export interface V1VehicleSafetyScoreResponse {
    /** Crash event count */
    crashCount?: number | undefined;
    /** Harsh acceleration event count */
    harshAccelCount?: number | undefined;
    /** Harsh braking event count */
    harshBrakingCount?: number | undefined;
    harshEvents?: Samsara.V1SafetyReportHarshEvent[] | undefined;
    /** Harsh turning event count */
    harshTurningCount?: number | undefined;
    /** The vehicle’s Safety Score for the requested period. Note that if the vehicle has zero drive time in this period, the Safety Score will be returned as 100. */
    safetyScore?: number | undefined;
    /** Safety Score Rank */
    safetyScoreRank?: string | undefined;
    /** Amount of time driven over the speed limit in milliseconds */
    timeOverSpeedLimitMs?: number | undefined;
    /** Total distance driven in meters */
    totalDistanceDrivenMeters?: number | undefined;
    /** Total harsh event count */
    totalHarshEventCount?: number | undefined;
    /** Amount of time driven in milliseconds */
    totalTimeDrivenMs?: number | undefined;
    /** Vehicle ID */
    vehicleId?: number | undefined;
}
