// This file was auto-generated by Fern from our API Definition.

export interface V1VisionRunByCameraResponseRunSummary {
    itemsPerMinute?: number | undefined;
    noReadCount?: number | undefined;
    rejectCount?: number | undefined;
    successCount?: number | undefined;
}
