/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * A list of synthetic engine seconds for the vehicle.
 */
export interface VehicleStatsListSyntheticEngineSeconds {
    decorations?: SamsaraApi.VehicleStatsDecorations;
    time: SamsaraApi.VehicleStatsAuxInputTime;
    value: SamsaraApi.VehicleStatsSyntheticEngineSecondsValue;
}
