/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * Vehicle OBD engine seconds reading.
 */
export interface VehicleStatsObdEngineSecondsWithDecoration {
    decorations?: SamsaraApi.VehicleStatsDecorations;
    time: SamsaraApi.Time;
    /** Number of seconds the vehicle's engine has been on according to the on-board diagnostics. */
    value: number;
}
