/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * The sensors configured on a vehicle
 */
export interface VehicleSensorConfiguration {
    areas?: Samsara.VehicleSensorConfigurationArea[];
    doors?: Samsara.VehicleSensorConfigurationDoor[];
}
