/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * True if the speed value is reported from the ECU. Speed value is reported from GPS otherwise.
 */
export type VehicleLocationIsEcuSpeed = boolean;
