// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Vehicle location event.
 */
export interface VehicleLocation {
    heading?: Samsara.VehicleLocationHeading | undefined;
    latitude: Samsara.VehicleLocationLatitude;
    longitude: Samsara.VehicleLocationLongitude;
    reverseGeo?: Samsara.ReverseGeo | undefined;
    speed?: Samsara.VehicleLocationSpeed | undefined;
    time: Samsara.Time;
}
