/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether vehicle spreader is enabled.
 */
export interface VehicleStatsResponseSpreaderOnState {
    /** UTC timestamp in RFC 3339 format. Example: `2020-01-27T07:06:25Z`. */
    time: string;
    /** Whether vehicle spreader is enabled. */
    value: VehicleStatsResponseSpreaderOnState.Value;
}

export namespace VehicleStatsResponseSpreaderOnState {
    /**
     * Whether vehicle spreader is enabled.
     */
    export type Value = "On" | "Off";
    export const Value = {
        On: "On",
        Off: "Off",
    } as const;
}
