// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Charging status for electric and hybrid vehicles. Not all EV and HEVs may report this field.
 */
export interface VehicleStatsEvChargingStatus {
    time: Samsara.Time;
    /**
     * Charging status for electric and hybrid vehicles. Statuses:
     *  unknown - 0,
     *  not charging - 1,
     *  charging - 2.
     */
    value: number;
}
