/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Air (ambient) temperature in milli celsius reading from material spreader.
 */
export interface VehicleStatsSpreaderAirTemp {
    time: Samsara.Time;
    /** Air (ambient) temperature in milli celsius reading from material spreader. */
    value: number;
}
