// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * The cumulative idling duration in milliseconds. Cumulative values always increase. For filtering of idling duration please use <a href="/api-reference/fuel-and-efficiency/idling/get-idling-events" target="_blank">the Idling Events API</a>.
 */
export interface VehicleStatsIdlingDurationMilliseconds {
    time: Samsara.Time;
    /** The cumulative idling duration in milliseconds. Cumulative values always increase. For filtering of idling duration please use <a href="/api-reference/fuel-and-efficiency/idling/get-idling-events" target="_blank">the Idling Events API</a>. */
    value: number;
}
