// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * Snow plow status (`Up` or `Down`), as read from the material spreader. Note: this is separate from plow status defined via auxInput.
 */
export interface VehicleStatsSpreaderPlowStatus {
    time: Samsara.Time;
    /** Snow plow status, as read from the material spreader */
    value: VehicleStatsSpreaderPlowStatus.Value;
}

export namespace VehicleStatsSpreaderPlowStatus {
    /** Snow plow status, as read from the material spreader */
    export const Value = {
        Up: "Up",
        Down: "Down",
    } as const;
    export type Value = (typeof Value)[keyof typeof Value];
}
