/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Whether vehicle spreader is enabled.
 */
export interface VehicleStatsSpreaderOnState {
    time: Samsara.Time;
    /** Whether vehicle spreader is enabled. */
    value: VehicleStatsSpreaderOnState.Value;
}

export namespace VehicleStatsSpreaderOnState {
    /**
     * Whether vehicle spreader is enabled.
     */
    export type Value = "On" | "Off";
    export const Value = {
        On: "On",
        Off: "Off",
    } as const;
}
