/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Readings from engine sensors
 */
export interface VehicleStatsFaultCodesPassengerMonitorStatus {
    catalyst?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    comprehensive?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    egr?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    evapSystem?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    fuel?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    heatedCatalyst?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    heatedO2Sensor?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    isoSaeReserved?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    misfire?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    /** Count of the number of sensors reporting N: Not Complete */
    notReadyCount?: number;
    o2Sensor?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
    secondaryAir?: Samsara.VehicleStatsFaultCodesPassengerMonitorStatusValue;
}
