/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether or not the vehicle is regulated, unregulated (non-CMV), or a mixed use unregulated vehicle. Valid values: `regulated`, `unregulated`, `mixed`.
 */
export type VehicleRegulationMode = "regulated" | "unregulated" | "mixed";
export const VehicleRegulationMode = {
    Regulated: "regulated",
    Unregulated: "unregulated",
    Mixed: "mixed",
} as const;
