/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Passenger vehicle DTC information
 */
export interface VehicleStatsFaultCodesPassengerDtc {
    /** The DTC description, if available. */
    dtcDescription?: string;
    /** The DTC identifier. */
    dtcId: number;
    /** The DTC short code, if available. */
    dtcShortCode?: string;
}
