// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * A vehicle and its most recent stat.
 */
export interface VehicleStatsResponseData {
    ambientAirTemperatureMilliC?: Samsara.VehicleStatsAmbientAirTempMilliC | undefined;
    auxInput1?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput10?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput11?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput12?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput13?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput2?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput3?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput4?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput5?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput6?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput7?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput8?: Samsara.VehicleStatsAuxInput | undefined;
    auxInput9?: Samsara.VehicleStatsAuxInput | undefined;
    barometricPressurePa?: Samsara.VehicleStatsBarometricPressurePa | undefined;
    batteryMilliVolts?: Samsara.VehicleStatsBatteryVoltage | undefined;
    defLevelMilliPercent?: Samsara.VehicleStatsDefLevelMilliPercent | undefined;
    ecuDoorStatus?: Samsara.VehicleStatsResponseEcuDoorStatus | undefined;
    ecuSpeedMph?: Samsara.VehicleStatsEcuSpeedMph | undefined;
    engineCoolantTemperatureMilliC?: Samsara.VehicleStatsEngineCoolantTempMilliC | undefined;
    engineImmobilizer?: Samsara.VehicleStatsEngineImmobilizer | undefined;
    engineLoadPercent?: Samsara.VehicleStatsEngineLoadPercent | undefined;
    engineOilPressureKPa?: Samsara.VehicleStatsEngineOilPressureKPa | undefined;
    engineRpm?: Samsara.VehicleStatsEngineRpm | undefined;
    engineState?: Samsara.VehicleStatsEngineState | undefined;
    evAverageBatteryTemperatureMilliCelsius?:
        | Samsara.VehicleStatsResponseEvAverageBatteryTemperatureMilliCelsius
        | undefined;
    evBatteryCurrentMilliAmp?: Samsara.VehicleStatsResponseEvBatteryCurrentMilliAmp | undefined;
    evBatteryStateOfHealthMilliPercent?: Samsara.VehicleStatsResponseEvBatteryStateOfHealthMilliPercent | undefined;
    evBatteryVoltageMilliVolt?: Samsara.VehicleStatsResponseEvBatteryVoltageMilliVolt | undefined;
    evChargingCurrentMilliAmp?: Samsara.VehicleStatsResponseEvChargingCurrentMilliAmp | undefined;
    evChargingEnergyMicroWh?: Samsara.VehicleStatsResponseEvChargingEnergyMicroWh | undefined;
    evChargingStatus?: Samsara.VehicleStatsResponseEvChargingStatus | undefined;
    evChargingVoltageMilliVolt?: Samsara.VehicleStatsResponseEvChargingVoltageMilliVolt | undefined;
    evConsumedEnergyMicroWh?: Samsara.VehicleStatsResponseEvConsumedEnergyMicroWh | undefined;
    evDistanceDrivenMeters?: Samsara.VehicleStatsResponseEvDistanceDrivenMeters | undefined;
    evRegeneratedEnergyMicroWh?: Samsara.VehicleStatsResponseEvRegeneratedEnergyMicroWh | undefined;
    evStateOfChargeMilliPercent?: Samsara.VehicleStatsResponseEvStateOfChargeMilliPercent | undefined;
    externalIds?: Samsara.VehicleExternalIds | undefined;
    faultCodes?: Samsara.VehicleStatsFaultCodes | undefined;
    fuelConsumedMilliliters?: Samsara.VehicleStatsFuelConsumedMilliliters | undefined;
    fuelPercent?: Samsara.VehicleStatsFuelPercent | undefined;
    gps?: Samsara.VehicleStatsGps | undefined;
    gpsDistanceMeters?: Samsara.VehicleStatsGpsDistanceMeters | undefined;
    gpsOdometerMeters?: Samsara.VehicleStatsGpsOdometerMeters | undefined;
    id: Samsara.VehicleId;
    idlingDurationMilliseconds?: Samsara.VehicleStatsIdlingDurationMilliseconds | undefined;
    intakeManifoldTemperatureMilliC?: Samsara.VehicleStatsIntakeManifoldTempMilliC | undefined;
    name: Samsara.VehicleName;
    nfcCardScan?: Samsara.VehicleStatsNfcCardScan | undefined;
    obdEngineSeconds?: Samsara.VehicleStatsObdEngineSeconds | undefined;
    obdOdometerMeters?: Samsara.VehicleStatsObdOdometerMeters | undefined;
    seatbeltDriver?: Samsara.VehicleStatsResponseSeatbeltDriver | undefined;
    spreaderActive?: Samsara.VehicleStatsResponseSpreaderActive | undefined;
    spreaderAirTemp?: Samsara.VehicleStatsResponseSpreaderAirTemp | undefined;
    spreaderBlastState?: Samsara.VehicleStatsResponseSpreaderBlastState | undefined;
    spreaderGranularName?: Samsara.VehicleStatsResponseSpreaderGranularName | undefined;
    spreaderGranularRate?: Samsara.VehicleStatsResponseSpreaderGranularRate | undefined;
    spreaderLiquidName?: Samsara.VehicleStatsResponseSpreaderLiquidName | undefined;
    spreaderLiquidRate?: Samsara.VehicleStatsResponseSpreaderLiquidRate | undefined;
    spreaderOnState?: Samsara.VehicleStatsResponseSpreaderOnState | undefined;
    spreaderPlowStatus?: Samsara.VehicleStatsResponseSpreaderPlowStatus | undefined;
    spreaderPrewetName?: Samsara.VehicleStatsResponseSpreaderPrewetName | undefined;
    spreaderPrewetRate?: Samsara.VehicleStatsResponseSpreaderPrewetRate | undefined;
    spreaderRoadTemp?: Samsara.VehicleStatsResponseSpreaderRoadTemp | undefined;
    syntheticEngineSeconds?: Samsara.VehicleStatsSyntheticEngineSeconds | undefined;
}
