/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Vehicle engine oil pressure reading.
 */
export interface VehicleStatsEngineOilPressureKPaWithDecoration {
    decorations?: Samsara.VehicleStatsDecorations;
    time: Samsara.Time;
    /** The engine oil pressure reading in kilopascals. */
    value: number;
}
