/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * Data for the synthetic engine seconds for the vehicle
 */
export interface VehicleStatsSyntheticEngineSeconds {
    decorations?: SamsaraApi.VehicleStatsDecorations;
    time: SamsaraApi.VehicleStatsAuxInputTime;
    value: SamsaraApi.VehicleStatsSyntheticEngineSecondsValue;
}
