// This file was auto-generated by Fern from our API Definition.

/**
 * Enum of monitor status:
 * -U: Unsupported
 * -N: Not Complete
 * -R: Complete
 */
export const VehicleStatsFaultCodesPassengerMonitorStatusValue = {
    N: "N",
    R: "R",
    U: "U",
} as const;
export type VehicleStatsFaultCodesPassengerMonitorStatusValue =
    (typeof VehicleStatsFaultCodesPassengerMonitorStatusValue)[keyof typeof VehicleStatsFaultCodesPassengerMonitorStatusValue];
