/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * A single vehicle.
 */
export interface VehicleResponse {
    data: SamsaraApi.Vehicle;
}
