// This file was auto-generated by Fern from our API Definition.

/**
 * Status of engine lights on J1939 vehicles.
 */
export interface VehicleStatsFaultCodesValueJ1939CheckEngineLights {
    /** True if the MIL status is nonzero. */
    emissionsIsOn: boolean;
    /** True if the engine protect lamp status is nonzero. */
    protectIsOn: boolean;
    /** True if the red lamp status is nonzero. */
    stopIsOn: boolean;
    /** True if the amber lamp status is nonzero. */
    warningIsOn: boolean;
}
