/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Road temperature reading in milli celsius from material spreader.
 */
export interface VehicleStatsSpreaderRoadTemp {
    time: Samsara.Time;
    /** Road temperature reading in milli celsius from material spreader. */
    value: number;
}
