/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Vehicle engine RPM reading.
 */
export interface VehicleStatsEngineRpmWithDecoration {
    decorations?: Samsara.VehicleStatsDecorations;
    time: Samsara.Time;
    /** The revolutions per minute of the engine. */
    value: number;
}
