/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * Data for the nfc card and the time that it was scanned.
 */
export interface VehicleStatsNfcCardScan {
    card: SamsaraApi.VehicleStatsNfcCardScanCard;
    time: SamsaraApi.VehicleStatsAuxInputTime;
}
