// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../index.js";

/**
 * A vehicle and its most recent stat.
 */
export interface VehicleStatsResponseData {
    ambientAirTemperatureMilliC?: Samsara.VehicleStatsAmbientAirTempMilliC;
    auxInput1?: Samsara.VehicleStatsAuxInput;
    auxInput10?: Samsara.VehicleStatsAuxInput;
    auxInput11?: Samsara.VehicleStatsAuxInput;
    auxInput12?: Samsara.VehicleStatsAuxInput;
    auxInput13?: Samsara.VehicleStatsAuxInput;
    auxInput2?: Samsara.VehicleStatsAuxInput;
    auxInput3?: Samsara.VehicleStatsAuxInput;
    auxInput4?: Samsara.VehicleStatsAuxInput;
    auxInput5?: Samsara.VehicleStatsAuxInput;
    auxInput6?: Samsara.VehicleStatsAuxInput;
    auxInput7?: Samsara.VehicleStatsAuxInput;
    auxInput8?: Samsara.VehicleStatsAuxInput;
    auxInput9?: Samsara.VehicleStatsAuxInput;
    barometricPressurePa?: Samsara.VehicleStatsBarometricPressurePa;
    batteryMilliVolts?: Samsara.VehicleStatsBatteryVoltage;
    defLevelMilliPercent?: Samsara.VehicleStatsDefLevelMilliPercent;
    ecuDoorStatus?: Samsara.VehicleStatsResponseEcuDoorStatus;
    ecuSpeedMph?: Samsara.VehicleStatsEcuSpeedMph;
    engineCoolantTemperatureMilliC?: Samsara.VehicleStatsEngineCoolantTempMilliC;
    engineImmobilizer?: Samsara.VehicleStatsEngineImmobilizer;
    engineLoadPercent?: Samsara.VehicleStatsEngineLoadPercent;
    engineOilPressureKPa?: Samsara.VehicleStatsEngineOilPressureKPa;
    engineRpm?: Samsara.VehicleStatsEngineRpm;
    engineState?: Samsara.VehicleStatsEngineState;
    evAverageBatteryTemperatureMilliCelsius?: Samsara.VehicleStatsResponseEvAverageBatteryTemperatureMilliCelsius;
    evBatteryCurrentMilliAmp?: Samsara.VehicleStatsResponseEvBatteryCurrentMilliAmp;
    evBatteryStateOfHealthMilliPercent?: Samsara.VehicleStatsResponseEvBatteryStateOfHealthMilliPercent;
    evBatteryVoltageMilliVolt?: Samsara.VehicleStatsResponseEvBatteryVoltageMilliVolt;
    evChargingCurrentMilliAmp?: Samsara.VehicleStatsResponseEvChargingCurrentMilliAmp;
    evChargingEnergyMicroWh?: Samsara.VehicleStatsResponseEvChargingEnergyMicroWh;
    evChargingStatus?: Samsara.VehicleStatsResponseEvChargingStatus;
    evChargingVoltageMilliVolt?: Samsara.VehicleStatsResponseEvChargingVoltageMilliVolt;
    evConsumedEnergyMicroWh?: Samsara.VehicleStatsResponseEvConsumedEnergyMicroWh;
    evDistanceDrivenMeters?: Samsara.VehicleStatsResponseEvDistanceDrivenMeters;
    evRegeneratedEnergyMicroWh?: Samsara.VehicleStatsResponseEvRegeneratedEnergyMicroWh;
    evStateOfChargeMilliPercent?: Samsara.VehicleStatsResponseEvStateOfChargeMilliPercent;
    externalIds?: Samsara.VehicleExternalIds;
    faultCodes?: Samsara.VehicleStatsFaultCodes;
    fuelConsumedMilliliters?: Samsara.VehicleStatsFuelConsumedMilliliters;
    fuelPercent?: Samsara.VehicleStatsFuelPercent;
    gps?: Samsara.VehicleStatsGps;
    gpsDistanceMeters?: Samsara.VehicleStatsGpsDistanceMeters;
    gpsOdometerMeters?: Samsara.VehicleStatsGpsOdometerMeters;
    id: Samsara.VehicleId;
    idlingDurationMilliseconds?: Samsara.VehicleStatsIdlingDurationMilliseconds;
    intakeManifoldTemperatureMilliC?: Samsara.VehicleStatsIntakeManifoldTempMilliC;
    name: Samsara.VehicleName;
    nfcCardScan?: Samsara.VehicleStatsNfcCardScan;
    obdEngineSeconds?: Samsara.VehicleStatsObdEngineSeconds;
    obdOdometerMeters?: Samsara.VehicleStatsObdOdometerMeters;
    seatbeltDriver?: Samsara.VehicleStatsResponseSeatbeltDriver;
    spreaderActive?: Samsara.VehicleStatsResponseSpreaderActive;
    spreaderAirTemp?: Samsara.VehicleStatsResponseSpreaderAirTemp;
    spreaderBlastState?: Samsara.VehicleStatsResponseSpreaderBlastState;
    spreaderGranularName?: Samsara.VehicleStatsResponseSpreaderGranularName;
    spreaderGranularRate?: Samsara.VehicleStatsResponseSpreaderGranularRate;
    spreaderLiquidName?: Samsara.VehicleStatsResponseSpreaderLiquidName;
    spreaderLiquidRate?: Samsara.VehicleStatsResponseSpreaderLiquidRate;
    spreaderOnState?: Samsara.VehicleStatsResponseSpreaderOnState;
    spreaderPlowStatus?: Samsara.VehicleStatsResponseSpreaderPlowStatus;
    spreaderPrewetName?: Samsara.VehicleStatsResponseSpreaderPrewetName;
    spreaderPrewetRate?: Samsara.VehicleStatsResponseSpreaderPrewetRate;
    spreaderRoadTemp?: Samsara.VehicleStatsResponseSpreaderRoadTemp;
    syntheticEngineSeconds?: Samsara.VehicleStatsSyntheticEngineSeconds;
}
