/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SamsaraApi from "../index.js";

/**
 * Details specific to Vehicle Detected.
 */
export interface VehicleDetectedResponseBody {
    cameraStream?: SamsaraApi.AlertObjectOnvifCameraStreamResponseBody;
}
