/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Vehicle engine coolant temperature reading.
 */
export interface VehicleStatsEngineCoolantTempMilliC {
    time: Samsara.Time;
    /** The engine coolant temperature reading in millidegree Celsius. */
    value: number;
}
