/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

/**
 * Vehicle engine state event.
 */
export interface VehicleStatsEngineStateWithDecoration {
    decorations?: Samsara.VehicleStatsDecorations;
    time: Samsara.Time;
    value: Samsara.VehicleStatsEngineStateSetting;
}
