/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Regenerated energy for electric and hybrid vehicles in microwatt hours. Not all EV and HEVs may report this field.
 */
export interface VehicleStatsResponseEvRegeneratedEnergyMicroWh {
    /** UTC timestamp in RFC 3339 format. Example: `2020-01-27T07:06:25Z`. */
    time: string;
    /** Regenerated energy for electric and hybrid vehicles in microwatt hours. */
    value: number;
}
