/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../index.js";

export interface WebhooksListWebhooksResponseBody {
    /** This is a list of Webhooks. */
    data: Samsara.WebhookResponseResponseBody[];
    pagination: Samsara.GoaPaginationResponseResponseBody;
}
