// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Samsara from "../../../index.js";

export declare namespace IssuesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class IssuesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<IssuesClient.Options>;

    constructor(options: IssuesClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns all issues data for the specified IDs.
     *
     *  <b>Rate limit:</b> 5 requests/sec (learn more about rate limits [here](/docs/rate-limits)).
     *
     * To use this endpoint, select **Read Issues** under the Forms category when creating or editing an API token. [Learn More.](/docs/authentication#scopes-for-api-tokens)
     *
     *
     *  **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.
     *
     * @param {Samsara.GetIssuesRequest} request
     * @param {IssuesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Samsara.UnauthorizedError}
     * @throws {@link Samsara.NotFoundError}
     * @throws {@link Samsara.MethodNotAllowedError}
     * @throws {@link Samsara.TooManyRequestsError}
     * @throws {@link Samsara.InternalServerError}
     * @throws {@link Samsara.NotImplementedError}
     * @throws {@link Samsara.BadGatewayError}
     * @throws {@link Samsara.ServiceUnavailableError}
     * @throws {@link Samsara.GatewayTimeoutError}
     *
     * @example
     *     await client.issues.getIssues()
     */
    public getIssues(
        request: Samsara.GetIssuesRequest = {},
        requestOptions?: IssuesClient.RequestOptions,
    ): core.HttpResponsePromise<Samsara.IssuesGetIssuesResponseBody> {
        return core.HttpResponsePromise.fromPromise(this.__getIssues(request, requestOptions));
    }

    private async __getIssues(
        request: Samsara.GetIssuesRequest = {},
        requestOptions?: IssuesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Samsara.IssuesGetIssuesResponseBody>> {
        const { ids, include } = request;
        const _queryParams: Record<string, unknown> = {
            ids,
            include,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Samsara-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SamsaraEnvironment.ProductionApi,
                "issues",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Samsara.IssuesGetIssuesResponseBody, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Samsara.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Samsara.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 405:
                    throw new Samsara.MethodNotAllowedError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Samsara.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Samsara.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 501:
                    throw new Samsara.NotImplementedError(_response.error.body as unknown, _response.rawResponse);
                case 502:
                    throw new Samsara.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Samsara.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Samsara.GatewayTimeoutError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SamsaraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/issues");
    }

    /**
     * Updates an instance of an issue.
     *
     *  <b>Rate limit:</b> 100 requests/min (learn more about rate limits [here](/docs/rate-limits)).
     *
     * To use this endpoint, select **Write Issues** under the Forms category when creating or editing an API token. [Learn More.](/docs/authentication#scopes-for-api-tokens)
     *
     *
     *  **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.
     *
     * @param {Samsara.IssuesPatchIssueRequestBody} request
     * @param {IssuesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Samsara.UnauthorizedError}
     * @throws {@link Samsara.NotFoundError}
     * @throws {@link Samsara.MethodNotAllowedError}
     * @throws {@link Samsara.TooManyRequestsError}
     * @throws {@link Samsara.InternalServerError}
     * @throws {@link Samsara.NotImplementedError}
     * @throws {@link Samsara.BadGatewayError}
     * @throws {@link Samsara.ServiceUnavailableError}
     * @throws {@link Samsara.GatewayTimeoutError}
     *
     * @example
     *     await client.issues.patchIssue({
     *         id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7"
     *     })
     */
    public patchIssue(
        request: Samsara.IssuesPatchIssueRequestBody,
        requestOptions?: IssuesClient.RequestOptions,
    ): core.HttpResponsePromise<Samsara.IssuesPatchIssueResponseBody> {
        return core.HttpResponsePromise.fromPromise(this.__patchIssue(request, requestOptions));
    }

    private async __patchIssue(
        request: Samsara.IssuesPatchIssueRequestBody,
        requestOptions?: IssuesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Samsara.IssuesPatchIssueResponseBody>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Samsara-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SamsaraEnvironment.ProductionApi,
                "issues",
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Samsara.IssuesPatchIssueResponseBody, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Samsara.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Samsara.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 405:
                    throw new Samsara.MethodNotAllowedError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Samsara.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Samsara.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 501:
                    throw new Samsara.NotImplementedError(_response.error.body as unknown, _response.rawResponse);
                case 502:
                    throw new Samsara.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Samsara.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Samsara.GatewayTimeoutError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SamsaraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/issues");
    }

    /**
     * Returns all issues data that has been created or modified for your organization based on the time parameters passed in. Results are paginated and are sorted by last modified date. If you include an endTime, the endpoint will return data up until that point (exclusive). If you don’t include an endTime, you can continue to poll the API real-time with the pagination cursor that gets returned on every call.
     *
     *  <b>Rate limit:</b> 5 requests/sec (learn more about rate limits [here](/docs/rate-limits)).
     *
     * To use this endpoint, select **Read Issues** under the Forms category when creating or editing an API token. [Learn More.](/docs/authentication#scopes-for-api-tokens)
     *
     *
     *  **Submit Feedback**: Likes, dislikes, and API feature requests should be filed as feedback in our <a href="https://forms.gle/zkD4NCH7HjKb7mm69" target="_blank">API feedback form</a>. If you encountered an issue or noticed inaccuracies in the API documentation, please <a href="https://www.samsara.com/help" target="_blank">submit a case</a> to our support team.
     *
     * @param {Samsara.GetIssuesStreamRequest} request
     * @param {IssuesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Samsara.UnauthorizedError}
     * @throws {@link Samsara.NotFoundError}
     * @throws {@link Samsara.MethodNotAllowedError}
     * @throws {@link Samsara.TooManyRequestsError}
     * @throws {@link Samsara.InternalServerError}
     * @throws {@link Samsara.NotImplementedError}
     * @throws {@link Samsara.BadGatewayError}
     * @throws {@link Samsara.ServiceUnavailableError}
     * @throws {@link Samsara.GatewayTimeoutError}
     *
     * @example
     *     await client.issues.getIssuesStream({
     *         startTime: "startTime"
     *     })
     */
    public getIssuesStream(
        request: Samsara.GetIssuesStreamRequest,
        requestOptions?: IssuesClient.RequestOptions,
    ): core.HttpResponsePromise<Samsara.IssuesGetIssuesStreamResponseBody> {
        return core.HttpResponsePromise.fromPromise(this.__getIssuesStream(request, requestOptions));
    }

    private async __getIssuesStream(
        request: Samsara.GetIssuesStreamRequest,
        requestOptions?: IssuesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Samsara.IssuesGetIssuesStreamResponseBody>> {
        const { startTime, endTime, after, status, assetIds, include, assignedToRouteStopIds } = request;
        const _queryParams: Record<string, unknown> = {
            startTime,
            endTime,
            after,
            status,
            assetIds,
            include,
            assignedToRouteStopIds,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Samsara-Version": requestOptions?.version }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SamsaraEnvironment.ProductionApi,
                "issues/stream",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Samsara.IssuesGetIssuesStreamResponseBody,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Samsara.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Samsara.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 405:
                    throw new Samsara.MethodNotAllowedError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Samsara.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Samsara.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 501:
                    throw new Samsara.NotImplementedError(_response.error.body as unknown, _response.rawResponse);
                case 502:
                    throw new Samsara.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new Samsara.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                case 504:
                    throw new Samsara.GatewayTimeoutError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SamsaraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/issues/stream");
    }
}
