/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SpeedingIntervalsStreamRequestQueryBy = "updatedAtTime" | "tripStartTime";
export const SpeedingIntervalsStreamRequestQueryBy = {
    UpdatedAtTime: "updatedAtTime",
    TripStartTime: "tripStartTime",
} as const;
