/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface HosDailyLogsRequest {
    /**
     *  A filter on the data based on this comma-separated list of driver IDs and externalIds. Example: `driverIds=1234,5678,payroll:4841`
     */
    driverIds?: string | string[];
    /**
     *  A start date in YYYY-MM-DD. This is a date only without an associated time. Example: `2019-06-13`. This is a required field
     */
    startDate?: string;
    /**
     *  An end date in YYYY-MM-DD. This is a date only without an associated time. Must be greater than or equal to the start date. Example: `2019-07-21`. This is a required field
     */
    endDate?: string;
    /**
     *  A filter on the data based on this comma-separated list of tag IDs. Example: `tagIds=1234,5678`
     */
    tagIds?: string;
    /**
     *  A filter on the data based on this comma-separated list of parent tag IDs, for use by orgs with tag hierarchies. Specifying a parent tag will implicitly include all descendent tags of the parent tag. Example: `parentTagIds=345,678`
     */
    parentTagIds?: string;
    /**
     * If value is `deactivated`, only drivers that are deactivated will appear in the response. This parameter will default to `active` if not provided (fetching only active drivers).  Valid values: `active`, `deactivated`
     */
    driverActivationStatus?: Samsara.HosDailyLogsRequestDriverActivationStatus;
    /**
     *  If specified, this should be the endCursor value from the previous page of results. When present, this request will return the next page of results that occur immediately after the previous page of results.
     */
    after?: string;
    /**
     * Expands the specified value(s) in the response object. Expansion populates additional fields in an object, if supported. Unsupported fields are ignored. To expand multiple fields, input a comma-separated list.
     *
     * Valid value: `vehicle`  Valid values: `vehicle`
     */
    expand?: "vehicle";
}
