// This file was auto-generated by Fern from our API Definition.

export const GetHosEldEventsRequestDriverActivationStatus = {
    Active: "active",
    Deactivated: "deactivated",
} as const;
export type GetHosEldEventsRequestDriverActivationStatus =
    (typeof GetHosEldEventsRequestDriverActivationStatus)[keyof typeof GetHosEldEventsRequestDriverActivationStatus];
