// This file was auto-generated by Fern from our API Definition.

export const GetJobsRequestStatus = {
    Active: "active",
    Scheduled: "scheduled",
    Completed: "completed",
} as const;
export type GetJobsRequestStatus = (typeof GetJobsRequestStatus)[keyof typeof GetJobsRequestStatus];
