// This file was auto-generated by Fern from our API Definition.

export const GetQualificationTypesRequestEntityType = {
    Worker: "worker",
    Asset: "asset",
} as const;
export type GetQualificationTypesRequestEntityType =
    (typeof GetQualificationTypesRequestEntityType)[keyof typeof GetQualificationTypesRequestEntityType];
