// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         startMs: 1000000,
 *         endMs: 1000000
 *     }
 */
export interface V1GetVehicleSafetyScoreRequest {
    /** Timestamp in milliseconds representing the start of the period to fetch, inclusive. Used in combination with endMs. Total duration (endMs - startMs) must be greater than or equal to 1 hour. */
    startMs: number;
    /** Timestamp in milliseconds representing the end of the period to fetch, inclusive. Used in combination with startMs. Total duration (endMs - startMs) must be greater than or equal to 1 hour. */
    endMs: number;
}
