/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         driverIds: [111, 222, 333],
 *         text: "This is a message."
 *     }
 */
export interface InlineObject2 {
    /** IDs of the drivers for whom the messages are sent to. */
    driverIds: number[];
    /** The text sent in the message. Max 2500 characters allowed. */
    text: string;
}
