// This file was auto-generated by Fern from our API Definition.

import * as Samsara from "../../src/api/index";
import { SamsaraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DriverVehicleAssignmentsClient", () => {
    test("getDriverVehicleAssignments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    assignedAtTime: "2019-06-13T19:08:25Z",
                    assignmentType: "invalid",
                    driver: { id: "45646", name: "Driver Bob" },
                    endTime: "2019-06-13T19:08:25Z",
                    isPassenger: true,
                    metadata: { sourceName: "ExternalSourceName" },
                    startTime: "2019-06-13T19:08:25Z",
                    vehicle: { id: "494123", name: "Fleet Truck #1" },
                },
            ],
            pagination: { endCursor: "MjkY", hasNextPage: true },
        };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.driverVehicleAssignments.getDriverVehicleAssignments({
            filterBy: "drivers",
        });
        expect(response).toEqual({
            data: [
                {
                    assignedAtTime: "2019-06-13T19:08:25Z",
                    assignmentType: "invalid",
                    driver: {
                        id: "45646",
                        name: "Driver Bob",
                    },
                    endTime: "2019-06-13T19:08:25Z",
                    isPassenger: true,
                    metadata: {
                        sourceName: "ExternalSourceName",
                    },
                    startTime: "2019-06-13T19:08:25Z",
                    vehicle: {
                        id: "494123",
                        name: "Fleet Truck #1",
                    },
                },
            ],
            pagination: {
                endCursor: "MjkY",
                hasNextPage: true,
            },
        });
    });

    test("getDriverVehicleAssignments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("getDriverVehicleAssignments (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("getDriverVehicleAssignments (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("getDriverVehicleAssignments (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("getDriverVehicleAssignments (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("getDriverVehicleAssignments (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(501)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("getDriverVehicleAssignments (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("getDriverVehicleAssignments (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("getDriverVehicleAssignments (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fleet/driver-vehicle-assignments")
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.getDriverVehicleAssignments({
                filterBy: "drivers",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });

    test("createDriverVehicleAssignment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "494123", vehicleId: "281474978683353" };
        const rawResponseBody = { data: { message: "Driver assignment was successfully submitted" } };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.driverVehicleAssignments.createDriverVehicleAssignment({
            driverId: "494123",
            vehicleId: "281474978683353",
        });
        expect(response).toEqual({
            data: {
                message: "Driver assignment was successfully submitted",
            },
        });
    });

    test("createDriverVehicleAssignment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("createDriverVehicleAssignment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("createDriverVehicleAssignment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("createDriverVehicleAssignment (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("createDriverVehicleAssignment (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("createDriverVehicleAssignment (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(501)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("createDriverVehicleAssignment (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("createDriverVehicleAssignment (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("createDriverVehicleAssignment (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.createDriverVehicleAssignment({
                driverId: "driverId",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });

    test("deleteDriverVehicleAssignments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "281474978683353" };

        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
            vehicleId: "281474978683353",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteDriverVehicleAssignments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("deleteDriverVehicleAssignments (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("deleteDriverVehicleAssignments (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("deleteDriverVehicleAssignments (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("deleteDriverVehicleAssignments (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("deleteDriverVehicleAssignments (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(501)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("deleteDriverVehicleAssignments (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("deleteDriverVehicleAssignments (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("deleteDriverVehicleAssignments (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.deleteDriverVehicleAssignments({
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });

    test("updateDriverVehicleAssignment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "494123", startTime: "2019-06-13T19:08:25Z", vehicleId: "281474978683353" };
        const rawResponseBody = { data: { message: "Driver assignment was successfully updated" } };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.driverVehicleAssignments.updateDriverVehicleAssignment({
            driverId: "494123",
            startTime: "2019-06-13T19:08:25Z",
            vehicleId: "281474978683353",
        });
        expect(response).toEqual({
            data: {
                message: "Driver assignment was successfully updated",
            },
        });
    });

    test("updateDriverVehicleAssignment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("updateDriverVehicleAssignment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("updateDriverVehicleAssignment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("updateDriverVehicleAssignment (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("updateDriverVehicleAssignment (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("updateDriverVehicleAssignment (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(501)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("updateDriverVehicleAssignment (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("updateDriverVehicleAssignment (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("updateDriverVehicleAssignment (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { driverId: "driverId", startTime: "startTime", vehicleId: "vehicleId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/fleet/driver-vehicle-assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.driverVehicleAssignments.updateDriverVehicleAssignment({
                driverId: "driverId",
                startTime: "startTime",
                vehicleId: "vehicleId",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });
});
