/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { SamsaraClient } from "../../src/Client";

describe("Issues", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({ token: "test", version: "2025-05-12", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    asset: {
                        entryType: "tracked",
                        externalIds: { externalIds: "externalIds" },
                        id: "id",
                        name: "name",
                    },
                    assignedTo: { id: "id", type: "driver" },
                    createdAtTime: "2024-01-15T09:30:00Z",
                    description: "description",
                    dueDate: "2024-01-15T09:30:00Z",
                    externalIds: { externalIds: "externalIds" },
                    id: "id",
                    issueSource: { id: "id", type: "form" },
                    mediaList: [
                        { id: "id", processingStatus: "unknown", url: "url", urlExpiresAt: "2024-01-15T09:30:00Z" },
                        { id: "id", processingStatus: "unknown", url: "url", urlExpiresAt: "2024-01-15T09:30:00Z" },
                    ],
                    priority: "low",
                    status: "open",
                    submittedAtTime: "2024-01-15T09:30:00Z",
                    submittedBy: { id: "id", type: "driver" },
                    title: "title",
                    updatedAtTime: "2024-01-15T09:30:00Z",
                },
                {
                    asset: {
                        entryType: "tracked",
                        externalIds: { externalIds: "externalIds" },
                        id: "id",
                        name: "name",
                    },
                    assignedTo: { id: "id", type: "driver" },
                    createdAtTime: "2024-01-15T09:30:00Z",
                    description: "description",
                    dueDate: "2024-01-15T09:30:00Z",
                    externalIds: { externalIds: "externalIds" },
                    id: "id",
                    issueSource: { id: "id", type: "form" },
                    mediaList: [
                        { id: "id", processingStatus: "unknown", url: "url", urlExpiresAt: "2024-01-15T09:30:00Z" },
                        { id: "id", processingStatus: "unknown", url: "url", urlExpiresAt: "2024-01-15T09:30:00Z" },
                    ],
                    priority: "low",
                    status: "open",
                    submittedAtTime: "2024-01-15T09:30:00Z",
                    submittedBy: { id: "id", type: "driver" },
                    title: "title",
                    updatedAtTime: "2024-01-15T09:30:00Z",
                },
            ],
        };
        server.mockEndpoint().get("/issues").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.issues.list();
        expect(response).toEqual({
            data: [
                {
                    asset: {
                        entryType: "tracked",
                        externalIds: {
                            externalIds: "externalIds",
                        },
                        id: "id",
                        name: "name",
                    },
                    assignedTo: {
                        id: "id",
                        type: "driver",
                    },
                    createdAtTime: "2024-01-15T09:30:00Z",
                    description: "description",
                    dueDate: "2024-01-15T09:30:00Z",
                    externalIds: {
                        externalIds: "externalIds",
                    },
                    id: "id",
                    issueSource: {
                        id: "id",
                        type: "form",
                    },
                    mediaList: [
                        {
                            id: "id",
                            processingStatus: "unknown",
                            url: "url",
                            urlExpiresAt: "2024-01-15T09:30:00Z",
                        },
                        {
                            id: "id",
                            processingStatus: "unknown",
                            url: "url",
                            urlExpiresAt: "2024-01-15T09:30:00Z",
                        },
                    ],
                    priority: "low",
                    status: "open",
                    submittedAtTime: "2024-01-15T09:30:00Z",
                    submittedBy: {
                        id: "id",
                        type: "driver",
                    },
                    title: "title",
                    updatedAtTime: "2024-01-15T09:30:00Z",
                },
                {
                    asset: {
                        entryType: "tracked",
                        externalIds: {
                            externalIds: "externalIds",
                        },
                        id: "id",
                        name: "name",
                    },
                    assignedTo: {
                        id: "id",
                        type: "driver",
                    },
                    createdAtTime: "2024-01-15T09:30:00Z",
                    description: "description",
                    dueDate: "2024-01-15T09:30:00Z",
                    externalIds: {
                        externalIds: "externalIds",
                    },
                    id: "id",
                    issueSource: {
                        id: "id",
                        type: "form",
                    },
                    mediaList: [
                        {
                            id: "id",
                            processingStatus: "unknown",
                            url: "url",
                            urlExpiresAt: "2024-01-15T09:30:00Z",
                        },
                        {
                            id: "id",
                            processingStatus: "unknown",
                            url: "url",
                            urlExpiresAt: "2024-01-15T09:30:00Z",
                        },
                    ],
                    priority: "low",
                    status: "open",
                    submittedAtTime: "2024-01-15T09:30:00Z",
                    submittedBy: {
                        id: "id",
                        type: "driver",
                    },
                    title: "title",
                    updatedAtTime: "2024-01-15T09:30:00Z",
                },
            ],
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({ token: "test", version: "2025-05-12", environment: server.baseUrl });
        const rawRequestBody = { id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7" };
        const rawResponseBody = {
            data: {
                asset: {
                    entryType: "tracked",
                    externalIds: { key: "value" },
                    id: "281474982859091",
                    name: "trailer 123",
                },
                assignedTo: { id: "938172", type: "driver" },
                createdAtTime: "2019-06-13T19:08:25Z",
                description: "Oil spill in left corner of SF1",
                dueDate: "2019-06-13T19:08:25Z",
                externalIds: { key: "value" },
                id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                issueSource: { id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7", type: "form" },
                mediaList: [
                    {
                        id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                        processingStatus: "unknown",
                        url: "https://samsara-forms-submission-media-uploads.s3.us-west-2.amazonaws.com/123456",
                        urlExpiresAt: "2019-06-13T19:08:25Z",
                    },
                ],
                priority: "low",
                status: "open",
                submittedAtTime: "2019-06-13T19:08:25Z",
                submittedBy: { id: "938172", type: "driver" },
                title: "Oil spill",
                updatedAtTime: "2019-06-13T19:08:25Z",
            },
        };
        server
            .mockEndpoint()
            .patch("/issues")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.issues.update({
            id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
        });
        expect(response).toEqual({
            data: {
                asset: {
                    entryType: "tracked",
                    externalIds: {
                        key: "value",
                    },
                    id: "281474982859091",
                    name: "trailer 123",
                },
                assignedTo: {
                    id: "938172",
                    type: "driver",
                },
                createdAtTime: "2019-06-13T19:08:25Z",
                description: "Oil spill in left corner of SF1",
                dueDate: "2019-06-13T19:08:25Z",
                externalIds: {
                    key: "value",
                },
                id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                issueSource: {
                    id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                    type: "form",
                },
                mediaList: [
                    {
                        id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                        processingStatus: "unknown",
                        url: "https://samsara-forms-submission-media-uploads.s3.us-west-2.amazonaws.com/123456",
                        urlExpiresAt: "2019-06-13T19:08:25Z",
                    },
                ],
                priority: "low",
                status: "open",
                submittedAtTime: "2019-06-13T19:08:25Z",
                submittedBy: {
                    id: "938172",
                    type: "driver",
                },
                title: "Oil spill",
                updatedAtTime: "2019-06-13T19:08:25Z",
            },
        });
    });
});
