// This file was auto-generated by Fern from our API Definition.

import * as Samsara from "../../src/api/index";
import { SamsaraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PlansClient", () => {
    test("createHubPlan (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "550e8400-e29b-41d4-a716-446655440000", name: "Weekly Plan - Week 15" };
        const rawResponseBody = {
            data: {
                createdAt: "2024-04-10T10:30:00Z",
                hubId: "550e8400-e29b-41d4-a716-446655440000",
                id: "950e8400-e29b-41d4-a716-446655440005",
                name: "Weekly Plan - Week 15",
                shiftStartTime: "2024-04-15T09:00:00Z",
                updatedAt: "2024-04-10T10:30:00Z",
            },
        };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.plans.createHubPlan({
            hubId: "550e8400-e29b-41d4-a716-446655440000",
            name: "Weekly Plan - Week 15",
        });
        expect(response).toEqual({
            data: {
                createdAt: "2024-04-10T10:30:00Z",
                hubId: "550e8400-e29b-41d4-a716-446655440000",
                id: "950e8400-e29b-41d4-a716-446655440005",
                name: "Weekly Plan - Week 15",
                shiftStartTime: "2024-04-15T09:00:00Z",
                updatedAt: "2024-04-10T10:30:00Z",
            },
        });
    });

    test("createHubPlan (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("createHubPlan (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("createHubPlan (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("createHubPlan (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("createHubPlan (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("createHubPlan (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(501)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("createHubPlan (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("createHubPlan (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("createHubPlan (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { hubId: "hubId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/hub/plan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plans.createHubPlan({
                hubId: "hubId",
                name: "name",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });

    test("listHubPlans (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    createdAt: "2024-04-10T10:30:00Z",
                    hubId: "550e8400-e29b-41d4-a716-446655440000",
                    id: "950e8400-e29b-41d4-a716-446655440005",
                    name: "Weekly Plan - Week 15",
                    shiftStartTime: "2024-04-15T09:00:00Z",
                    updatedAt: "2024-04-10T10:30:00Z",
                },
            ],
            pagination: { endCursor: "YXJyYXljb25uZWN0aW9uOjEwMA==", hasNextPage: false },
        };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.plans.listHubPlans({
            hubId: "hubId",
        });
        expect(response).toEqual({
            data: [
                {
                    createdAt: "2024-04-10T10:30:00Z",
                    hubId: "550e8400-e29b-41d4-a716-446655440000",
                    id: "950e8400-e29b-41d4-a716-446655440005",
                    name: "Weekly Plan - Week 15",
                    shiftStartTime: "2024-04-15T09:00:00Z",
                    updatedAt: "2024-04-10T10:30:00Z",
                },
            ],
            pagination: {
                endCursor: "YXJyYXljb25uZWN0aW9uOjEwMA==",
                hasNextPage: false,
            },
        });
    });

    test("listHubPlans (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("listHubPlans (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("listHubPlans (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(405).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("listHubPlans (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("listHubPlans (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("listHubPlans (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(501).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("listHubPlans (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("listHubPlans (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("listHubPlans (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/hub/plans").respondWith().statusCode(504).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.plans.listHubPlans({
                hubId: "hubId",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });
});
