/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { SamsaraClient } from "../../src/Client";

describe("TrainingAssignments", () => {
    test("stream", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({ token: "test", version: "2025-05-12", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    completedAtTime: "2019-06-13T19:08:25Z",
                    course: {
                        id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                        revisionId: "1214a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                    },
                    createdAtTime: "2019-06-13T19:08:25Z",
                    createdById: "user-4392",
                    deletedAtTime: "2019-06-13T19:08:25Z",
                    dueAtTime: "2019-06-13T19:08:25Z",
                    durationMinutes: 5883292486284507000,
                    id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                    isCompletedLate: true,
                    isOverdue: true,
                    learner: { id: "938172", type: "driver" },
                    scorePercent: 0.20511986669994858,
                    startedAtTime: "2019-06-13T19:08:25Z",
                    status: "notStarted",
                    updatedAtTime: "2019-06-13T19:08:25Z",
                    updatedById: "user-3112",
                },
            ],
            pagination: { endCursor: "MjkY", hasNextPage: true },
        };
        server
            .mockEndpoint()
            .get("/training-assignments/stream")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.trainingAssignments.stream({
            startTime: "startTime",
        });
        expect(response).toEqual({
            data: [
                {
                    completedAtTime: "2019-06-13T19:08:25Z",
                    course: {
                        id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                        revisionId: "1214a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                    },
                    createdAtTime: "2019-06-13T19:08:25Z",
                    createdById: "user-4392",
                    deletedAtTime: "2019-06-13T19:08:25Z",
                    dueAtTime: "2019-06-13T19:08:25Z",
                    durationMinutes: 5883292486284507000,
                    id: "9814a1fa-f0c6-408b-bf85-51dc3bc71ac7",
                    isCompletedLate: true,
                    isOverdue: true,
                    learner: {
                        id: "938172",
                        type: "driver",
                    },
                    scorePercent: 0.20511986669994858,
                    startedAtTime: "2019-06-13T19:08:25Z",
                    status: "notStarted",
                    updatedAtTime: "2019-06-13T19:08:25Z",
                    updatedById: "user-3112",
                },
            ],
            pagination: {
                endCursor: "MjkY",
                hasNextPage: true,
            },
        });
    });
});
