// This file was auto-generated by Fern from our API Definition.

import { SamsaraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("VehicleLocationsClient", () => {
    test("getVehicleLocations", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "112",
                    location: {
                        heading: 120,
                        latitude: 122.142,
                        longitude: -93.343,
                        speed: 48.3,
                        time: "2020-01-27T07:06:25Z",
                    },
                    name: "Truck A7",
                },
            ],
            pagination: { endCursor: "MjkY", hasNextPage: true },
        };
        server
            .mockEndpoint()
            .get("/fleet/vehicles/locations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.vehicleLocations.getVehicleLocations();
        expect(response).toEqual({
            data: [
                {
                    id: "112",
                    location: {
                        heading: 120,
                        latitude: 122.142,
                        longitude: -93.343,
                        speed: 48.3,
                        time: "2020-01-27T07:06:25Z",
                    },
                    name: "Truck A7",
                },
            ],
            pagination: {
                endCursor: "MjkY",
                hasNextPage: true,
            },
        });
    });

    test("getVehicleLocationsFeed", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "112",
                    locations: [
                        {
                            heading: 120,
                            latitude: 122.142,
                            longitude: -93.343,
                            speed: 48.3,
                            time: "2020-01-27T07:06:25Z",
                        },
                    ],
                    name: "Truck A7",
                },
            ],
            pagination: { endCursor: "MjkY", hasNextPage: true },
        };
        server
            .mockEndpoint()
            .get("/fleet/vehicles/locations/feed")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.vehicleLocations.getVehicleLocationsFeed();
        expect(response).toEqual({
            data: [
                {
                    id: "112",
                    locations: [
                        {
                            heading: 120,
                            latitude: 122.142,
                            longitude: -93.343,
                            speed: 48.3,
                            time: "2020-01-27T07:06:25Z",
                        },
                    ],
                    name: "Truck A7",
                },
            ],
            pagination: {
                endCursor: "MjkY",
                hasNextPage: true,
            },
        });
    });

    test("getVehicleLocationsHistory", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "112",
                    locations: [
                        {
                            heading: 120,
                            latitude: 122.142,
                            longitude: -93.343,
                            speed: 48.3,
                            time: "2020-01-27T07:06:25Z",
                        },
                    ],
                    name: "Truck A7",
                },
            ],
            pagination: { endCursor: "MjkY", hasNextPage: true },
        };
        server
            .mockEndpoint()
            .get("/fleet/vehicles/locations/history")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.vehicleLocations.getVehicleLocationsHistory({
            startTime: "startTime",
            endTime: "endTime",
        });
        expect(response).toEqual({
            data: [
                {
                    id: "112",
                    locations: [
                        {
                            heading: 120,
                            latitude: 122.142,
                            longitude: -93.343,
                            speed: 48.3,
                            time: "2020-01-27T07:06:25Z",
                        },
                    ],
                    name: "Truck A7",
                },
            ],
            pagination: {
                endCursor: "MjkY",
                hasNextPage: true,
            },
        });
    });
});
