// This file was auto-generated by Fern from our API Definition.

import * as Samsara from "../../src/api/index";
import { SamsaraClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("listWebhooks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    customHeaders: [{ key: "format", value: "xcmol-532" }],
                    eventTypes: ["AddressCreated", "AddressCreated", "AddressCreated", "AddressCreated"],
                    id: "23918",
                    name: "Webhook-123",
                    secretKey: "11121-31231-1231212",
                    url: "https://www.webhook-123.com/webhook/listener",
                    version: "2018-01-01",
                },
            ],
            pagination: { endCursor: "MjkY", hasNextPage: true },
        };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.listWebhooks();
        expect(response).toEqual({
            data: [
                {
                    customHeaders: [
                        {
                            key: "format",
                            value: "xcmol-532",
                        },
                    ],
                    eventTypes: ["AddressCreated", "AddressCreated", "AddressCreated", "AddressCreated"],
                    id: "23918",
                    name: "Webhook-123",
                    secretKey: "11121-31231-1231212",
                    url: "https://www.webhook-123.com/webhook/listener",
                    version: "2018-01-01",
                },
            ],
            pagination: {
                endCursor: "MjkY",
                hasNextPage: true,
            },
        });
    });

    test("listWebhooks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("listWebhooks (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("listWebhooks (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(405).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("listWebhooks (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("listWebhooks (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("listWebhooks (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(501).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("listWebhooks (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("listWebhooks (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("listWebhooks (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks").respondWith().statusCode(504).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });

    test("postWebhooks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "Webhook-123", url: "https://www.Webhook-123.com/webhook/listener" };
        const rawResponseBody = {
            customHeaders: [{ key: "format", value: "xcmol-532" }],
            eventTypes: ["AddressCreated", "AddressCreated", "AddressCreated", "AddressCreated"],
            id: "23918",
            name: "Webhook-123",
            secretKey: "11121-31231-1231212",
            url: "https://www.webhook-123.com/webhook/listener",
            version: "2018-01-01",
        };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.postWebhooks({
            name: "Webhook-123",
            url: "https://www.Webhook-123.com/webhook/listener",
        });
        expect(response).toEqual({
            customHeaders: [
                {
                    key: "format",
                    value: "xcmol-532",
                },
            ],
            eventTypes: ["AddressCreated", "AddressCreated", "AddressCreated", "AddressCreated"],
            id: "23918",
            name: "Webhook-123",
            secretKey: "11121-31231-1231212",
            url: "https://www.webhook-123.com/webhook/listener",
            version: "2018-01-01",
        });
    });

    test("postWebhooks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("postWebhooks (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("postWebhooks (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("postWebhooks (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("postWebhooks (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("postWebhooks (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(501)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("postWebhooks (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("postWebhooks (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("postWebhooks (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.postWebhooks({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });

    test("getWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            customHeaders: [{ key: "format", value: "xcmol-532" }],
            eventTypes: ["AddressCreated", "AddressCreated", "AddressCreated", "AddressCreated"],
            id: "23918",
            name: "Webhook-123",
            secretKey: "11121-31231-1231212",
            url: "https://www.webhook-123.com/webhook/listener",
            version: "2018-01-01",
        };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.getWebhook({
            id: "id",
        });
        expect(response).toEqual({
            customHeaders: [
                {
                    key: "format",
                    value: "xcmol-532",
                },
            ],
            eventTypes: ["AddressCreated", "AddressCreated", "AddressCreated", "AddressCreated"],
            id: "23918",
            name: "Webhook-123",
            secretKey: "11121-31231-1231212",
            url: "https://www.webhook-123.com/webhook/listener",
            version: "2018-01-01",
        });
    });

    test("getWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("getWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("getWebhook (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(405).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("getWebhook (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("getWebhook (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("getWebhook (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(501).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("getWebhook (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("getWebhook (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("getWebhook (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/webhooks/id").respondWith().statusCode(504).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });

    test("deleteWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(200).build();

        const response = await client.webhooks.deleteWebhook({
            id: "id",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("deleteWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("deleteWebhook (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(405).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("deleteWebhook (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("deleteWebhook (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("deleteWebhook (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(501).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("deleteWebhook (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("deleteWebhook (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("deleteWebhook (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/webhooks/id").respondWith().statusCode(504).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });

    test("patchWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            customHeaders: [{ key: "format", value: "xcmol-532" }],
            eventTypes: ["AddressCreated", "AddressCreated", "AddressCreated"],
            id: "23918",
            name: "Webhook-123",
            secretKey: "11121-31231-1231212",
            url: "https://www.webhook-123.com/webhook/listener",
            version: "2018-01-01",
        };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.patchWebhook({
            id: "id",
        });
        expect(response).toEqual({
            customHeaders: [
                {
                    key: "format",
                    value: "xcmol-532",
                },
            ],
            eventTypes: ["AddressCreated", "AddressCreated", "AddressCreated"],
            id: "23918",
            name: "Webhook-123",
            secretKey: "11121-31231-1231212",
            url: "https://www.webhook-123.com/webhook/listener",
            version: "2018-01-01",
        });
    });

    test("patchWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.UnauthorizedError);
    });

    test("patchWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.NotFoundError);
    });

    test("patchWebhook (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.MethodNotAllowedError);
    });

    test("patchWebhook (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.TooManyRequestsError);
    });

    test("patchWebhook (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.InternalServerError);
    });

    test("patchWebhook (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(501)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.NotImplementedError);
    });

    test("patchWebhook (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.BadGatewayError);
    });

    test("patchWebhook (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.ServiceUnavailableError);
    });

    test("patchWebhook (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/webhooks/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.patchWebhook({
                id: "id",
            });
        }).rejects.toThrow(Samsara.GatewayTimeoutError);
    });
});
