// This file was auto-generated by Fern from our API Definition.

import { SamsaraClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("AssetsClient", () => {
    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new SamsaraClient({
            maxRetries: 0,
            token: "test",
            version: "2025-06-11",
            environment: server.baseUrl,
        });

        const rawResponseBody = "";
        server
            .mockEndpoint()
            .delete("/industrial/assets/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.industrial.assets.delete({
            id: "id",
        });
        expect(response).toEqual("");
    });
});
