/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateUserRequest {
    /** The authentication type the user uses to authenticate. To use SAML this organization must have a configured SAML integration. Valid values: `default`, `saml`. */
    authType?: UpdateUserRequest.AuthType;
    /** For users with temporary access, this is the expiration datetime in RFC3339 format */
    expireAt?: string;
    /** The first and last name of the user. */
    name?: string;
    /** The list of roles that applies to this user. A user may have "organizational" roles, which apply to the user at the organizational level, and "tag-specific" roles, which apply to the user for a given tag. */
    roles?: Samsara.CreateUserRequestRoles[];
}

export namespace UpdateUserRequest {
    /**
     * The authentication type the user uses to authenticate. To use SAML this organization must have a configured SAML integration. Valid values: `default`, `saml`.
     */
    export type AuthType = "default" | "saml";
    export const AuthType = {
        Default: "default",
        Saml: "saml",
    } as const;
}
