// This file was auto-generated by Fern from our API Definition.

export const GetTripsRequestCompletionStatus = {
    InProgress: "inProgress",
    Completed: "completed",
    All: "all",
} as const;
export type GetTripsRequestCompletionStatus =
    (typeof GetTripsRequestCompletionStatus)[keyof typeof GetTripsRequestCompletionStatus];
