/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Samsara from "../../../../index.js";

/**
 * @example
 *     {
 *         entityType: "driver"
 *     }
 */
export interface AttributesDeleteRequest {
    /**
     * Denotes the type of entity, driver or asset.
     */
    entityType: Samsara.AttributesDeleteRequestEntityType;
}
