// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../../../../index.js";

/**
 * @example
 *     {
 *         entityType: "driver"
 *     }
 */
export interface DeleteAttributesRequest {
    /** Denotes the type of entity, driver or asset. */
    entityType: Samsara.DeleteAttributesRequestEntityType;
}
