// This file was auto-generated by Fern from our API Definition.

import type * as Samsara from "../../../../index.js";

/**
 * @example
 *     {
 *         entityType: "driver"
 *     }
 */
export interface UpdateAttributeRequest {
    /** Denotes the data type of the attribute's values. Valid values: `single-select`, `multi-select`, `text`, `freeform-multi-select`, `number`, `date`. */
    attributeType?: UpdateAttributeRequest.AttributeType;
    /** Entities that will be applied to this attribute */
    entities?: Samsara.CreateAttributeRequestEntities[];
    /** Denotes the type of entity, driver or asset. */
    entityType: UpdateAttributeRequest.EntityType;
    /** Name */
    name?: string;
    /** Number values that can be associated with this attribute */
    numberValues?: number[];
    /** String values that can be associated with this attribute */
    stringValues?: string[];
}

export namespace UpdateAttributeRequest {
    /** Denotes the data type of the attribute's values. Valid values: `single-select`, `multi-select`, `text`, `freeform-multi-select`, `number`, `date`. */
    export const AttributeType = {
        SingleSelect: "single-select",
        MultiSelect: "multi-select",
        Text: "text",
        FreeformMultiSelect: "freeform-multi-select",
        Number: "number",
        Date: "date",
    } as const;
    export type AttributeType = (typeof AttributeType)[keyof typeof AttributeType];
    /** Denotes the type of entity, driver or asset. */
    export const EntityType = {
        Driver: "driver",
        Asset: "asset",
    } as const;
    export type EntityType = (typeof EntityType)[keyof typeof EntityType];
}
